import { setTimeout as sleep } from 'node:timers/promises';
import path from 'node:path';
import { Store } from './store.ts';
import { executeTask, planTask, redact, reviewTask } from './providers.ts';
import type { Gate, Plan, Review, Task } from './types.ts';
export interface Providers{plan:(t:Task,s:AbortSignal)=>Promise<Plan>;execute:(t:Task,a:(n:string,x:unknown)=>Promise<boolean>,s:AbortSignal)=>Promise<string>;review:(t:Task,s:AbortSignal)=>Promise<Review>}
export const providers:Providers={plan:planTask,execute:executeTask,review:reviewTask};
const alwaysBlockedTools=new Set(['delete_file','remove_file','deploy','send_message']);
function safeProjectTool(name:string,args:unknown){if(alwaysBlockedTools.has(name))return false;const root=path.resolve(process.env.ORCHESTRATOR_PROJECT_DIR||'');if(!root)return false;const values:string[]=[];const collect=(v:unknown)=>{if(typeof v==='string')values.push(v);else if(Array.isArray(v))v.forEach(collect);else if(v&&typeof v==='object')Object.values(v).forEach(collect)};collect(args);const blockedPath=/(^|[\\/])(\.env(?:\.|$)|\.git|data|tokens?|credentials?|secrets?)([\\/]|$)/i;const destructive=/(^|[;&|]\s*)(sudo\s+|rm\s+-|git\s+(reset|clean|stash|commit|push)|npm\s+publish|[^\s]*deploy\b)|\b(DROP|TRUNCATE|DELETE\s+FROM|UPDATE\s+\w+\s+SET)\b|\b(curl|wget)\b[^\n]*(--request|-X)\s*(POST|PUT|PATCH|DELETE)/i;return values.every(v=>!blockedPath.test(v)&&!destructive.test(v)&&(!path.isAbsolute(v)||path.resolve(v)===root||path.resolve(v).startsWith(root+path.sep)))}
export async function runTask(store:Store,task:Task,p=providers,signal=new AbortController().signal){const id=task.id;async function gate(kind:Gate,details:string,autoSafe=false){const current=store.get(id);if(kind==='TOOL'&&autoSafe&&(current.acceptAllReadOnly||current.auto)){store.event(id,'AUTO_ACCEPT',details,'OWNER_POLICY');return false}if(kind==='PLAN'&&current.auto&&current.round>1){store.event(id,'AUTO_ACCEPT',details,'OWNER_POLICY');return false}const a=store.gate(id,kind,redact(details));while(!signal.aborted){const d=store.approval(a.id).decision;if(d==='REJECT')throw new Error('Owner rejected the task.');if(d==='ACCEPT'||d==='ACCEPT_ALL')return true;await sleep(250,undefined,{signal})}throw new Error('Server stopped.')}try{for(;;){let t=store.get(id);const plan=JSON.parse(redact(JSON.stringify(await p.plan(t,signal)))) as Plan;store.tx(()=>{const c=store.get(id);store.db.prepare('UPDATE tasks SET body=? WHERE id=?').run(JSON.stringify({...c,plan,report:null,review:null}),id);store.event(id,'PLAN',JSON.stringify(plan))});await gate('PLAN',JSON.stringify(plan,null,2));t=store.transition(id,'RUNNING');const report=redact(await p.execute(t,async(n,a)=>{const gated=await gate('TOOL',JSON.stringify({tool:n,arguments:a},null,2),safeProjectTool(n,a));if(gated)store.transition(id,'RUNNING');return true},signal));t=store.transition(id,'REVIEWING',{report});const review=JSON.parse(redact(JSON.stringify(await p.review(t,signal)))) as Review;store.tx(()=>{const c=store.get(id);store.db.prepare('UPDATE tasks SET body=? WHERE id=?').run(JSON.stringify({...c,review}),id);store.event(id,'REVIEW',JSON.stringify(review))});if(t.auto&&review.verdict==='HUMAN'&&review.nextPrompt.trim()&&plan.risk==='LOW')store.event(id,'AUTO_CONTINUE_HUMAN',JSON.stringify({summary:review.summary,nextPrompt:review.nextPrompt}),'OWNER_POLICY');if(!t.auto||review.verdict!=='DONE'&&(plan.risk==='HIGH'||review.verdict==='HUMAN'&&!review.nextPrompt.trim()))await gate('REVIEW',JSON.stringify(review,null,2));if(review.verdict==='DONE'){store.transition(id,'COMPLETED');return}if(review.verdict==='HUMAN'&&!review.nextPrompt.trim()){store.transition(id,'COMPLETED');return}if(t.round>=t.maxRounds){if(t.auto&&t.maxRounds<25){store.tx(()=>{const c=store.get(id);store.db.prepare('UPDATE tasks SET body=? WHERE id=?').run(JSON.stringify({...c,maxRounds:c.maxRounds+1}),id);store.event(id,'AUTO_EXTEND',JSON.stringify({from:c.maxRounds,to:c.maxRounds+1}),'OWNER_POLICY')})}else await gate('REVIEW',JSON.stringify({...review,reason:'Round limit reached. Approve to continue.'},null,2))}store.transition(id,'PLANNING',{round:t.round+1})}}catch(e){if(signal.reason==='OWNER_PAUSE')store.pause(id);else if(signal.reason==='OWNER_STOP')store.stop(id);else store.fail(id,redact(e instanceof Error?e.message:'Workflow failed'))}}
