'use client';
import ConnectionControls from '../components/ConnectionControls';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import * as M from './model';
import { loadWorkspace, saveWorkspace } from './storage';
import { downloadExcel, downloadWord } from './exports';
import s from './hub.module.css';
const NAV = [['⌂', 'Command Centre'], ['▦', 'Projects'], ['✦', 'Task Library'], ['▤', 'Documents'], ['Q', 'Queries'], ['◫', 'Reports'], ['◇', 'Suggestions'], ['⚙', 'Settings']] as const;
type Page = typeof NAV[number][1];
type Modal = {
    kind: 'tender' | 'revision' | 'query' | 'suggestion' | 'custom' | 'task' | 'reports' | 'document' | 'query-edit' | 'archive';
    task?: number;
    reportId?: string;
    documentId?: string;
    queryId?: string;
};
const fieldLabels: Record<M.RateField, string> = { quantity: 'Approved quantity', listPrice: 'Base list price / unit', discount: 'Discount %', freight: 'Freight / unit', insurance: 'Insurance / unit', packing: 'Packing / unit', unloading: 'Unloading / unit', taxPercent: 'Input GST %', recoverablePercent: 'Recoverable GST %', wastagePercent: 'Wastage %', labour: 'Labour / unit', tools: 'Tools / unit', plant: 'Plant / unit', consumables: 'Consumables / unit', testing: 'Testing / unit', overheadPercent: 'Overhead %', contingencyPercent: 'Contingency %', profitPercent: 'Profit %' };
const text = (fd: FormData, key: string) => String(fd.get(key) ?? '').trim();
const number = (fd: FormData, key: string) => text(fd, key) === '' ? null : Number(fd.get(key));
function Field({ label, name, value = '', type = 'text', required = false, min, max, options, wide = false }: {
    label: string;
    name: string;
    value?: string | number;
    type?: string;
    required?: boolean;
    min?: number;
    max?: number;
    options?: readonly string[];
    wide?: boolean;
}) {
    return <label className={wide ? s.wide : undefined}>{label}{required ? '*' : ''}{options ? <select name={name} defaultValue={value}>{options.map(o => <option key={o}>{o}</option>)}</select> : type === 'textarea' ? <textarea name={name} defaultValue={value} required={required}/> : <input name={name} type={type} defaultValue={value} required={required} min={min} max={max} step={type === 'number' ? 'any' : undefined}/>}</label>;
}
function Dialog({ title, eyebrow, close, children }: {
    title: string;
    eyebrow: string;
    close: () => void;
    children: ReactNode;
}) {
    const ref = useRef<HTMLDivElement>(null);
    useEffect(() => { const old = document.activeElement as HTMLElement | null; ref.current?.focus(); return () => old?.focus(); }, []);
    return <div className={s.backdrop} onMouseDown={e => { if (e.target === e.currentTarget)
        close(); }}><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={s.dialog} onKeyDown={e => { if (e.key === 'Escape')
        close(); if (e.key === 'Tab') {
        const els = ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), a[href]');
        if (!els?.length)
            return;
        const first = els[0], last = els[els.length - 1];
        if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) {
            e.preventDefault();
            last.focus();
        }
        else if (!e.shiftKey && document.activeElement === last) {
            e.preventDefault();
            first.focus();
        }
    } }}><button className={s.close} onClick={close} aria-label="Close dialog">×</button><span className={s.eyebrow}>{eyebrow}</span><h2>{title}</h2>{children}</div></div>;
}
function Table({ table }: {
    table: M.Table;
}) { return <section className={s.reportTable}><h3>{table.title}</h3><div className={s.tableScroll}><table><thead><tr>{table.headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{table.rows.length ? table.rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j}>{c}</td>)}</tr>) : <tr><td colSpan={table.headers.length}>No evidence available</td></tr>}</tbody></table></div></section>; }
function downloadFile(d: M.Document) { const u = URL.createObjectURL(d.file), a = document.createElement('a'); a.href = u; a.download = d.name; a.click(); setTimeout(() => URL.revokeObjectURL(u), 10000); }
function FilePreview({ doc }: {
    doc: M.Document;
}) { const [url, setUrl] = useState(''), [content, setContent] = useState(''); useEffect(() => { const u = URL.createObjectURL(doc.file); setUrl(u); if (/\.(txt|csv)$/i.test(doc.name))
    doc.file.slice(0, 100000).text().then(setContent); return () => URL.revokeObjectURL(u); }, [doc]); return <><p>{doc.name} · {doc.revision} · {doc.status}</p><p className={s.hash}>SHA256 {doc.sha256}</p>{/\.pdf$/i.test(doc.name) ? <iframe className={s.pdf} src={url} title={doc.name}/> : content ? <pre className={s.pre}>{content}</pre> : <p>Office, CAD and ZIP files download for viewing. No content has been extracted.</p>}<button onClick={() => downloadFile(doc)}>Download original file</button></>; }
export default function TenderHub() {
    const [w, setW] = useState<M.Workspace>(M.emptyWorkspace), [page, setPage] = useState<Page>('Command Centre'), [modal, setModal] = useState<Modal | null>(null), [category, setCategory] = useState('All tasks'), [search, setSearch] = useState<string | null>(null), [projectSearch, setProjectSearch] = useState(''), [mobileNav, setMobileNav] = useState(false), [loaded, setLoaded] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [enabled, setEnabled] = useState(true), [audience, setAudience] = useState<M.Audience>('Internal');
    const busyRef = useRef(false);
    const active = w.projects.find(p => p.id === w.activeId && !p.archived), docs = w.documents.filter(d => d.projectId === active?.id && !d.deleted), ready = docs.filter(d => d.status === 'Ready'), queries = w.queries.filter(q => q.projectId === active?.id), reports = w.reports.filter(r => r.projectId === active?.id), projects = w.projects.filter(p => !p.archived);
    const close = () => { if (!busyRef.current) {
        setModal(null);
        setError('');
    } };
    const go = (p: Page) => { setPage(p); setMobileNav(false); setSearch(null); setCategory('All tasks'); setError(''); };
    const open = (m: Modal) => { setError(''); setModal(m); };
    useEffect(() => { loadWorkspace().then(x => { setW(x); setLoaded(true); }).catch(e => { setError(String(e)); }); }, []);
    useEffect(() => { const k = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setSearch(x => x === null ? '' : null);
    } if (e.key === 'Escape') {
        setSearch(null);
        setMobileNav(false);
    } }; window.addEventListener('keydown', k); return () => window.removeEventListener('keydown', k); }, []);
    useEffect(() => { let alive = true; const verify = () => fetch('/api/tender-hub/access', { cache: 'no-store' }).then(r => { if (alive)
        setEnabled(r.ok); }).catch(() => { if (alive)
        setEnabled(false); }); void verify(); const t = setInterval(verify, 15000); return () => { alive = false; clearInterval(t); }; }, []);
    async function commit(next: M.Workspace, message = 'Saved locally') {
        if (busyRef.current)
            throw Error('Save already in progress');
        if (!enabled)
            throw Error('Tender Hub is disabled');
        busyRef.current = true;
        setBusy(true);
        setError('');
        try {
            const r = await fetch('/api/tender-hub/access', { cache: 'no-store' });
            if (!r.ok) {
                setEnabled(false);
                throw Error('Tender Hub disabled; saved data preserved');
            }
            const saved = await saveWorkspace(next);
            setW(saved);
            setNotice(message);
            return saved;
        }
        catch (e) {
            setError(e instanceof Error ? e.message : String(e));
            throw e;
        }
        finally {
            busyRef.current = false;
            setBusy(false);
        }
    }
    async function act(f: () => Promise<unknown>) { try {
        await f();
    }
    catch (e) {
        setError(e instanceof Error ? e.message : String(e));
    } }
    const save = (e: FormEvent<HTMLFormElement>, f: (fd: FormData) => Promise<unknown>) => { e.preventDefault(); void act(() => f(new FormData(e.currentTarget))); };
    async function documentRecord(file: File, fd?: FormData): Promise<M.Document> {
        if (!active)
            throw Error('Select a PID before uploading');
        const err = M.fileError(file.name, file.size);
        if (err)
            throw Error(`${file.name}: ${err}`);
        const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', await file.arrayBuffer())), b => b.toString(16).padStart(2, '0')).join('');
        return { id: M.id(), projectId: active.id, name: file.name, size: file.size, mime: file.type, sha256: hash, file, createdAt: new Date().toISOString(), revision: fd ? text(fd, 'revision') : 'Original', number: fd ? text(fd, 'number') : '', source: fd ? text(fd, 'source') : 'Tender', category: fd ? text(fd, 'category') : 'Tender document', status: 'Ready', supersedes: fd ? text(fd, 'supersedes') : '', queryId: fd ? text(fd, 'queryId') : '' };
    }
    async function upload(files: FileList | File[]) { if (busyRef.current)
        return; let next = w; for (const file of Array.from(files)) {
        next = M.addRevision(next, await documentRecord(file));
    } await commit(next, 'Original files saved locally. Extraction and SharePoint sync are not connected.'); }
    const selectProject = (id: string) => void act(() => commit({ ...w, activeId: id }, 'Active PID selected'));
    const selector = <label className={s.selector}>ACTIVE PROJECT<select aria-label="ACTIVE PROJECT" value={active?.id ?? ''} disabled={busy} onChange={e => selectProject(e.target.value)}><option value="">Select PID workspace</option>{projects.map(p => <option value={p.id} key={p.id}>{p.pid} · {p.name}</option>)}</select></label>;
    const actionButtons = (label: string) => <div className={s.actions}><button type="button" onClick={close} disabled={busy}>Cancel</button><button className={s.primary} type="submit" disabled={busy}>{busy ? 'Saving…' : label}</button></div>;
    const heading = (eyebrow: string, title: string, description: string, action?: ReactNode) => <div className={s.pageHeading}><div><span className={s.eyebrow}>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>;
    const tasks = <><div className={s.sectionTitle}><div><span className={s.eyebrow}>PREDEFINED AGENT WORKFLOWS</span><h2>What do you want to perform?</h2></div><div className={s.tabs}>{['All tasks', 'Technical', 'Commercial', 'Reports'].map(c => <button className={category === c ? s.selected : ''} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div></div><div className={s.taskGrid}>{M.TASKS.map((t, i) => (category === 'All tasks' || t[2] === category) && <button key={t[0]} className={s.taskCard} onClick={() => open({ kind: 'task', task: i })}><span className={s.taskNumber}>{String(i + 1).padStart(2, '0')}</span><span><strong>{t[0]}</strong><small>{t[1]}</small><em>{t[2]}</em><small className={s.audience}>{t[3]}</small></span><span>↗</span></button>)}</div></>;
    const packIndices = [3, 9, 10, 11];
    const packs = <div className={s.packs}>{packIndices.map((i, n) => <button key={i} onClick={() => open({ kind: 'task', task: i })}><span className={s.taskNumber}>{['C', 'I', '₹', 'B'][n]}</span><strong>{['Customer Technical Compliance', 'Internal Commercial Compliance', 'Finance Management Sheet', 'Final Bid & Estimation Pack'][n]}</strong><small>{M.TASKS[i][1]}</small><em>RUN ONLY THIS →</em></button>)}</div>;
    const dropzone = <label className={`${s.dropzone} ${!active ? s.inactive : ''}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (active && !busy)
        void act(() => upload(e.dataTransfer.files)); }}><span>⇧</span><strong>Drop tender files here</strong><small>or click to browse PDF, Excel, Word, ZIP, CAD, TXT</small><small>Maximum 30 MB per file</small><input aria-label="Tender documents" type="file" accept={M.ACCEPT} multiple disabled={!active || busy} onChange={e => { if (e.target.files)
        void act(() => upload(e.target.files!)); e.target.value = ''; }}/></label>;
    const selectedReport = reports.find(r => r.id === modal?.reportId) ?? reports.at(-1);
    const stale = (r: M.Report) => r.documentHashes.length !== ready.length || r.documentHashes.some(h => !ready.some(d => d.sha256 === h));
    const saveReport = async (title: string, tables: M.Table[], out: M.Audience, rate?: M.Report['rate']) => { if (!active)
        throw Error('Select a PID'); const r: M.Report = { id: M.id(), projectId: active.id, title, audience: out, createdAt: new Date().toISOString(), status: 'Local calculation — unverified inputs', tables, documentHashes: ready.map(d => d.sha256), rate }; await commit({ ...w, reports: [...w.reports, r] }, 'Saved this report only. No external task ran.'); setAudience(out === 'Both' ? 'Internal' : out); setModal({ kind: 'reports', reportId: r.id }); };
    if (!loaded)
        return <main className={s.loading}><h1>EstimaPro</h1><p>{error || 'Loading local workspace…'}</p>{error && <button onClick={() => location.reload()}>Retry</button>}</main>;
    if (!enabled)
        return <main className={s.loading}><h1>Tender Hub disabled or unavailable</h1><p>Saved local data is preserved. Enable Estimation → Tender Hub in Settings → Modules &amp; Features.</p><a href="/">Open existing application</a><button onClick={() => location.reload()}>Check again</button></main>;
    return <div className={s.hub}>
  {mobileNav && <button className={s.navShade} aria-label="Close navigation" onClick={() => setMobileNav(false)}/>}
  <aside className={`${s.sidebar} ${mobileNav ? s.navOpen : ''}`}><div className={s.brand}><span>ET</span><div><strong>EstimaPro</strong><small>TENDER INTELLIGENCE</small></div></div><nav aria-label="Primary navigation"><span className={s.eyebrow}>WORKSPACE</span>{NAV.map(([icon, p]) => <button key={p} className={page === p ? s.navActive : ''} onClick={() => go(p)}><span>{icon}</span>{p}{p === 'Reports' && <small>{reports.length}</small>}{p === 'Suggestions' && <small>{w.suggestions.filter(x => x.status === 'Pending Approval').length}</small>}</button>)}</nav><div className={s.sidebarBottom}><div className={s.aiCard}><span className={s.eyebrow}>AI CORE</span><strong>Local workspace ready</strong><small>AI backend not connected</small></div><div className={s.profile}><span>BJ</span><div><strong>Local owner workspace</strong><small>Single browser · no shared access</small></div><a href="/" aria-label="Open Bansil Books">↗</a></div></div></aside>
  <div className={s.main}><header className={s.topbar}><button className={s.menu} aria-label="Open navigation" onClick={() => setMobileNav(x => !x)}>☰</button><span className={s.breadcrumb}>Electrical Tender Hub / <strong>{page}</strong></span><button className={s.searchButton} aria-label="Search projects, files, queries, reports, tasks and suggestions" onClick={() => setSearch('')}>⌕ <span>Search projects, files, queries</span><small>⌘ K</small></button><button aria-label="Open suggestion approvals" onClick={() => go('Suggestions')}>♧</button><button className={s.primary} onClick={() => open({ kind: 'tender' })}>＋ New Tender</button></header>
  <div className={s.localBanner}>Local copy · Original files and records stay in this browser · Zoho WRITE = 0</div>
  <main className={s.content}>
  {error && <div className={s.error} role="alert">{error}</div>}{notice && <div className={s.notice} role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notification">×</button></div>}
  {page === 'Command Centre' && <>{heading('LIVE TENDER CONTROL', 'Good evening, Balkrishna.', 'Select a PID, upload tender documents and run a defined audit or estimation task.', selector)}<div className={s.stats}>{[['▦', 'ACTIVE PROJECTS', String(projects.length).padStart(2, '0'), 'Stored tender records'], ['▤', 'DOCUMENTS INDEXED', String(ready.length), 'Ready originals; content extraction pending'], ['!', 'CRITICAL GAPS', '—', 'Technical audit not run'], ['₹', 'BID READINESS', `${active?.bidReadiness ?? 0}%`, active?.status ?? 'Select a PID']].map(([icon, label, value, detail]) => <article key={label}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><small>{detail}</small></div></article>)}</div><section className={s.bidWorkspace}><span className={s.eyebrow}>{active?.pid ?? 'NO ACTIVE PID'} · CURRENT BID WORKSPACE</span><h2>{active?.name ?? 'Create your first tender'}</h2><p>{active ? `${active.client} · ${active.location} · Due ${active.dueDate || 'Not provided'}` : 'No tender data has been imported from the original site.'}</p><div className={s.steps}>{['Intake', 'Audit', 'Compliance', 'Costing', 'QC', 'Bid'].map((x, i) => <span key={x}><b>{i + 1}</b>{x}</span>)}</div></section><div className={s.dashboardGrid}><section>{tasks}</section><aside className={s.rightColumn}><section className={s.card}><span className={s.eyebrow}>PID FILE CENTRE</span><h2>Documents <small>{docs.length}</small></h2>{dropzone}{ready.slice(0, 4).map(d => <button className={s.documentCard} key={d.id} onClick={() => open({ kind: 'document', documentId: d.id })}><span>{d.name.split('.').at(-1)?.toUpperCase()}</span><strong>{d.name}</strong><small>{(d.size / 1024).toFixed(1)} KB · Ready · Open ↗</small></button>)}{!docs.length && <p>No files in this PID yet.</p>}<button onClick={() => go('Documents')}>View complete document register →</button></section><section className={s.card}><span className={s.eyebrow}>DECISION QUEUE</span><h2>Attention required</h2>{[['Technical findings', 2], ['Commercial exposure', 9], ['Customer clarifications', 4]].map(([label, i]) => <div className={s.queue} key={label}><strong>{label}</strong><button onClick={() => open({ kind: 'task', task: Number(i) })}>Review</button></div>)}</section></aside></div><div className={s.sectionTitle}><h2>Report packs</h2><button onClick={() => go('Reports')}>View all reports</button></div>{packs}</>}
  {page === 'Projects' && <>{heading('TENDER REGISTER', 'Projects', 'Create, find and open every electrical tender workspace.', <button className={s.primary} onClick={() => open({ kind: 'tender' })}>＋ Add New Tender</button>)}<input className={s.projectSearch} aria-label="Search tenders" placeholder="Search PID, client, tender number, location or owner" value={projectSearch} onChange={e => setProjectSearch(e.target.value)}/><section className={s.card}><div className={s.tableScroll}><table><thead><tr><th>PID / TENDER</th><th>CLIENT & LOCATION</th><th>STATUS</th><th>READINESS</th><th /></tr></thead><tbody>{projects.filter(p => Object.values(p).join(' ').toLowerCase().includes(projectSearch.toLowerCase())).map(p => <tr key={p.id}><td><strong>{p.pid}</strong><p>{p.name}</p></td><td>{p.client}<p>{p.location}</p></td><td>{p.status}<p>{p.priority} priority</p></td><td>{p.bidReadiness}%</td><td><button onClick={() => selectProject(p.id)}>Open workspace</button></td></tr>)}</tbody></table></div>{!projects.length && <p>No tenders yet. Create your first PID.</p>}</section>{active && <section className={s.card}><span className={s.eyebrow}>{active.pid} · ACTIVE TENDER</span><h2>{active.name}</h2><div className={s.details}>{[['Client', active.client], ['Location', active.location], ['Estimator / Owner', active.owner], ['Submission date', active.dueDate || 'Not provided'], ['Estimated value', M.money(active.estimatedValue)], ['Documents', String(docs.length)]].map(([k, v]) => <div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className={s.actions}><button onClick={() => go('Documents')}>Documents</button><button onClick={() => open({ kind: 'custom' })}>Custom Task</button><button onClick={() => go('Task Library')}>Tasks →</button></div><p>SharePoint repository: not connected in this local copy.</p><div className={s.danger}><strong>OWNER DANGER ZONE</strong><p>Archive this local PID and preserve its records for recovery.</p><button onClick={() => open({ kind: 'archive' })}>Archive PID…</button></div></section>}{w.projects.some(p => p.archived) && <section className={s.card}><h2>Archived tenders</h2>{w.projects.filter(p => p.archived).map(p => <div className={s.queue} key={p.id}>{p.pid} · {p.name}<button onClick={() => void act(() => commit({ ...w, projects: w.projects.map(x => x.id === p.id ? { ...x, archived: false } : x), activeId: p.id }, 'PID restored'))}>Restore</button></div>)}</section>}</>}
  {page === 'Task Library' && <>{heading('CONTROLLED AI WORKFLOWS', 'Task Library', 'Choose a predefined workflow or give the agent your own tender task in natural language.', <button className={s.primary} onClick={() => open({ kind: 'custom' })}>＋ Ask Agent</button>)}{selector}<section className={s.customBanner}><span className={s.eyebrow}>AI · OPEN CUSTOM TASK</span><h2>Give the tender agent any task in your own words</h2><p>Review a controlled plan against Ready documents. AI execution needs a backend connection.</p><button className={s.primary} onClick={() => open({ kind: 'custom' })}>Ask Tender Agent →</button></section>{tasks}</>}
  {page === 'Documents' && <>{heading('PID FILE CENTRE', 'Documents & Revisions', 'Preserve original files, register each revision and link customer, vendor or internal query replies.', <button className={s.primary} disabled={!active} onClick={() => open({ kind: 'revision' })}>＋ Upload Revision</button>)}{selector}<section className={s.card}><h2>Upload to {active?.pid ?? 'selected PID'}</h2>{dropzone}</section><section className={s.card}><span className={s.eyebrow}>REVISION-CONTROLLED REGISTER</span><h2>{docs.length} registered files</h2><p>Ready means stored locally. Content extraction and external sync remain pending.</p><div className={s.tableScroll}><table><thead><tr><th>FILE / REVISION</th><th>SOURCE / CATEGORY</th><th>SIZE</th><th>STATUS / SHAREPOINT</th><th>ACTION</th></tr></thead><tbody>{docs.map(d => <tr key={d.id}><td><button className={s.textButton} onClick={() => open({ kind: 'document', documentId: d.id })}>{d.name}</button><p>{d.number || 'Document no. not set'} · {d.revision}</p><small className={s.hash}>{d.sha256}</small></td><td>{d.source}<p>{d.category}</p></td><td>{(d.size / 1024).toFixed(1)} KB</td><td>{d.status}<p>Sync not connected</p></td><td><button onClick={() => open({ kind: 'document', documentId: d.id })}>Open</button><button onClick={() => void act(() => commit({ ...w, documents: w.documents.map(x => x.id === d.id ? { ...x, deleted: true } : x) }, 'File moved to local archive'))}>Archive</button></td></tr>)}</tbody></table></div>{!docs.length && <p>No files registered.</p>}{w.documents.filter(d => d.projectId === active?.id && d.deleted).map(d => <div className={s.queue} key={d.id}>Archived: {d.name}<button onClick={() => void act(() => commit({ ...w, documents: w.documents.map(x => x.id === d.id ? { ...x, deleted: false } : x) }, 'Restored file; prior revision status preserved'))}>Restore</button></div>)}</section></>}
  {page === 'Queries' && <>{heading('TECHNICAL CORRESPONDENCE CONTROL', 'Queries & Replies', 'Register customer, vendor and internal queries; preserve replies and verify drafts before manual sending.', <button className={s.primary} disabled={!active} onClick={() => open({ kind: 'query' })}>＋ New Query</button>)}{selector}<section className={s.customBanner}><span className={s.eyebrow}>SAFE EMAIL WORKFLOW</span><h2>Manual inbox mode active</h2><p>Receive → Match PID → Draft → Verify → Manual send. Email is not connected. This copy never sends automatically.</p></section><div className={s.stats}>{[['OPEN / ACTIVE', queries.filter(q => !['Closed', 'Ready to send'].includes(q.status)).length], ['REPLIES RECEIVED', queries.filter(q => q.reply).length], ['PENDING VERIFICATION', queries.filter(q => q.draft && !q.verified).length], ['READY TO SEND', queries.filter(q => q.verified).length]].map(([label, n]) => <article key={label}><div><small>{label}</small><strong>{n}</strong></div></article>)}</div><section className={s.card}><h2>{active?.pid ?? 'No PID'} · {queries.length} queries</h2>{queries.map(q => <button className={s.queryCard} key={q.id} onClick={() => open({ kind: 'query-edit', queryId: q.id })}><strong>{q.subject}</strong><small>{q.source} · {q.priority} · {q.status} · {q.dueDate || 'No due date'}</small><p>{q.requirement}</p></button>)}{!queries.length && <p>No technical queries registered.</p>}</section></>}
  {page === 'Reports' && <>{heading('CONTROLLED OUTPUTS · ONE REPORT PER RUN', 'Reports', 'Select the exact report to generate. Only that selected workflow runs for the active PID.', <button disabled={!reports.length} onClick={() => open({ kind: 'reports' })}>Open Saved Reports</button>)}{selector}{packs}<section className={s.card}><h2>Saved report history</h2>{reports.map(r => <button className={s.queryCard} key={r.id} onClick={() => { setAudience(r.audience === 'Both' ? 'Internal' : r.audience); open({ kind: 'reports', reportId: r.id }); }}><strong>{r.title}</strong><small>{r.status} · {r.audience} · {new Date(r.createdAt).toLocaleDateString('en-IN')} {stale(r) ? '· STALE — document register changed' : ''}</small></button>)}{!reports.length && <p>No reports saved. No original-site results have been fabricated or imported.</p>}</section></>}
  {page === 'Suggestions' && <>{heading('CONTROLLED CHANGE MANAGEMENT', 'Suggestions & Approval', 'Submit requests and problems for local owner review.', <button className={s.primary} onClick={() => open({ kind: 'suggestion' })}>＋ Submit Suggestion</button>)}<section className={s.customBanner}><h2>Owner-controlled implementation policy</h2><p>Every submission starts as Pending Approval. Approved items enter the queue; mark Implemented only after verification. These local records do not grant access or trigger implementation.</p></section><div className={s.stats}>{['Pending Approval', 'Approved', 'Implemented'].map(x => <article key={x}><div><small>{x.toUpperCase()}</small><strong>{w.suggestions.filter(v => v.status === x).length}</strong></div></article>)}</div>{w.suggestions.map(v => <section className={s.card} key={v.id}><span className={s.eyebrow}>{v.type} · {v.priority} · {v.status}</span><h2>{v.title}</h2><p>{v.description}</p><div className={s.details}><div><small>Expected result</small>{v.expected || 'Not provided'}</div><div><small>Business impact</small>{v.impact || 'Not provided'}</div><div><small>Page / Module</small>{v.module || 'Not provided'}</div></div><div className={s.actions}>{(v.status === 'Pending Approval' ? ['Rejected', 'Approved'] : v.status === 'Approved' ? ['Rejected', 'Implemented'] : ['Pending Approval']).map(status => <button key={status} onClick={() => void act(() => commit({ ...w, suggestions: w.suggestions.map(x => x.id === v.id ? M.transitionSuggestion(x, status as M.Suggestion['status']) : x) }, 'Local review status saved'))}>{status === 'Approved' ? 'Approve for implementation' : status === 'Rejected' ? 'Reject' : status === 'Pending Approval' ? 'Reopen' : 'Mark verified & implemented'}</button>)}</div></section>)}{!w.suggestions.length && <section className={s.card}><h2>No suggestions yet</h2><p>Submit a feature request, improvement or problem report for review.</p></section>}</>}
  {page === 'Settings' && <><section className={s.card}><ConnectionControls/></section>{heading('OWNER ADMINISTRATION', 'Settings & Secure Integrations', 'Control repository automation, internal pricing references and access.')}<section className={s.card}><span className={s.eyebrow}>MICROSOFT 365 · OWNER CONTROLLED · NOT CONNECTED</span><h2>SharePoint Tender Repository</h2><p>Target and document library are not configured for this local copy.</p><div className={s.details}>{[['01 Automatic PID structure', '01 Tender Input · 02 Revisions · 03 Queries · 04 Supplier Quotes · 05 Estimation · 06 Reports'], ['02 Controlled price intelligence', 'List Prices · Supplier Quotations · Historical Costing · Approved Bids'], ['03 Commercial confidentiality', 'Customer exports omit internal rates, discounts, margins and vendor costs.']].map(([k, v]) => <div key={k}><strong>{k}</strong><p>{v}</p></div>)}</div><p>Connection, credentials, folder creation and external sync require a dedicated server integration. No secrets are accepted or stored in this browser.</p><button disabled>Configure server connection</button></section><section className={s.card}><h2>Two-step secure login</h2><p>Original site: module permissions plus a separate private-site invitation. This local copy has no shared user authentication. Access administration remains unavailable.</p><button disabled>Add User</button></section><section className={s.card}><h2>OpenAI API Connection</h2><p>Backend not connected. The original reports describe owner validation and AES-256-GCM encrypted server storage; this copy does not claim to reproduce that service.</p><button disabled>Validate & Connect</button></section><section className={s.card}><h2>Local storage & feature control</h2><p>Records and original file bytes are saved in IndexedDB for this browser and origin. Clearing browser data removes them. Multi-user sharing and canonical Phase 4C extraction are not connected.</p><a href="/">Open Bansil Books settings → Modules &amp; Features</a><button onClick={() => void act(async () => { setW(await loadWorkspace()); setNotice('Reloaded saved local workspace'); })}>Refresh saved workspace</button></section></>}
  </main></div>
 {search !== null && <Dialog title="Global search" eyebrow="ALL PROJECTS · CURRENT PID RECORDS · TASKS · SUGGESTIONS" close={() => setSearch(null)}><input autoFocus aria-label="Search workspace" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search PID, client, document, report or workflow"/>{!search.trim() ? <p>Start typing to search</p> : <div className={s.searchResults}>{projects.filter(p => `${p.pid} ${p.name} ${p.client} ${p.tenderNumber} ${p.location} ${p.owner}`.toLowerCase().includes(search.toLowerCase())).map(p => <button key={p.id} onClick={() => { selectProject(p.id); go('Projects'); }}><strong>{p.pid} · {p.name}</strong><small>Project · {p.client}</small></button>)}{docs.filter(d => d.name.toLowerCase().includes(search.toLowerCase())).map(d => <button key={d.id} onClick={() => { setSearch(null); open({ kind: 'document', documentId: d.id }); }}>{d.name}<small>Document · {d.revision}</small></button>)}{queries.filter(q => `${q.subject} ${q.requirement} ${q.reply}`.toLowerCase().includes(search.toLowerCase())).map(q => <button key={q.id} onClick={() => { setSearch(null); open({ kind: 'query-edit', queryId: q.id }); }}>{q.subject}<small>Query · {q.status}</small></button>)}{reports.filter(r => `${r.title} ${JSON.stringify(r.tables)}`.toLowerCase().includes(search.toLowerCase())).map(r => <button key={r.id} onClick={() => { setSearch(null); setAudience(r.audience === 'Both' ? 'Internal' : r.audience); open({ kind: 'reports', reportId: r.id }); }}>{r.title}<small>Report · {r.status}</small></button>)}{M.TASKS.map((t, i) => `${t[0]} ${t[1]}`.toLowerCase().includes(search.toLowerCase()) && <button key={t[0]} onClick={() => { setSearch(null); open({ kind: 'task', task: i }); }}>{t[0]}<small>Task · {t[3]}</small></button>)}{w.suggestions.filter(v => `${v.title} ${v.description}`.toLowerCase().includes(search.toLowerCase())).map(v => <button key={v.id} onClick={() => go('Suggestions')}>{v.title}<small>Suggestion · {v.status}</small></button>)}<p>End of search results</p></div>}</Dialog>}
 {modal && <Dialog title={modal.kind === 'task' ? M.TASKS[modal.task ?? 0][0] : ({ tender: 'New tender', revision: 'Upload revised document', query: 'New technical query', 'query-edit': 'Query & Reply', suggestion: 'New suggestion', custom: 'Ask the Tender Agent', reports: 'Analysis & Report Centre', document: 'Original document', archive: 'Archive PID' } as Record<string, string>)[modal.kind]} eyebrow={modal.kind === 'task' ? `${String((modal.task ?? 0) + 1).padStart(2, '0')} · ${M.TASKS[modal.task ?? 0][2].toUpperCase()} WORKFLOW` : 'CONTROLLED LOCAL WORKSPACE'} close={close}>
 {error && <p className={s.error} role="alert">{error}</p>}
 {modal.kind === 'tender' && <form onSubmit={e => save(e, async (fd) => { const p: M.Project = { id: M.id(), pid: text(fd, 'pid'), name: text(fd, 'name'), client: text(fd, 'client'), location: text(fd, 'location'), owner: text(fd, 'owner'), tenderNumber: text(fd, 'tenderNumber'), status: text(fd, 'status'), dueDate: text(fd, 'dueDate'), estimatedValue: number(fd, 'estimatedValue') ?? 0, bidReadiness: number(fd, 'bidReadiness') ?? 0, priority: text(fd, 'priority'), notes: text(fd, 'notes') }; const errs = M.projectErrors(p, w.projects); if (errs.length)
            throw Error(errs.join('; ')); await commit({ ...w, projects: [...w.projects, p], activeId: p.id }); close(); go('Projects'); })}><p>Create the PID record, then register original files in Documents.</p><div className={s.formGrid}><Field label="PID No." name="pid" required value={M.nextPid(w.projects, Number(new Intl.DateTimeFormat('en', {year:'numeric', timeZone:'Asia/Kolkata'}).format(new Date())))}/><Field label="Tender Number" name="tenderNumber"/><Field label="Tender / Work Description" name="name" required wide/><Field label="Client" name="client" required/><Field label="Location" name="location" required/><Field label="Estimator / Owner" name="owner" value="Balkrishn Joshi"/><Field label="Status" name="status" value="Draft" options={M.STATUSES}/><Field label="Submission Date" name="dueDate" type="date"/><Field label="Estimated Value (₹)" name="estimatedValue" type="number" min={0} value={0}/><Field label="Bid Readiness %" name="bidReadiness" type="number" min={0} max={100} value={0}/><Field label="Priority" name="priority" value="Medium" options={M.PRIORITIES}/><Field label="Scope / Clarification / Risk Notes" name="notes" type="textarea" wide/></div>{actionButtons('Save Tender')}</form>}
 {modal.kind === 'revision' && <form onSubmit={e => save(e, async (fd) => { const file = fd.get('file'); if (!(file instanceof File) || !file.size)
            throw Error('Select revision document'); const d = await documentRecord(file, fd); if (!d.revision)
            throw Error('Revision is required'); await commit(M.addRevision(w, d), 'Revision stored; earlier original preserved and superseded'); close(); })}><p>The new file becomes Ready. The linked earlier file remains in history and is marked Superseded. Superseded files are excluded from new runs.</p><div className={s.formGrid}><label className={s.wide}>Revision document*<input name="file" type="file" accept={M.ACCEPT} required/></label><Field label="Document number" name="number"/><Field label="Revision" name="revision" required/><Field label="Source" name="source" value="Customer" options={['Customer', 'Vendor', 'Internal', 'Tender']}/><Field label="Category" name="category" value="Revised Drawing" options={['Revised Drawing', 'Revised BOQ', 'Revised Specification', 'Query Reply', 'Vendor Offer', 'Other Revision']}/><label className={s.wide}>Supersedes earlier file<select name="supersedes"><option value="">No earlier file / first revision</option>{ready.map(d => <option key={d.id} value={d.id}>{d.name} · {d.revision}</option>)}</select></label><label className={s.wide}>Link to technical query<select name="queryId"><option value="">Not linked to a query</option>{queries.map(q => <option key={q.id} value={q.id}>{q.subject}</option>)}</select></label></div>{actionButtons('Save Revision')}</form>}
 {modal.kind === 'query' && <form onSubmit={e => save(e, async (fd) => { if (!active)
            throw Error('Select PID'); if (!text(fd, 'subject') || !text(fd, 'requirement'))
            throw Error('Subject and query required'); const q: M.Query = { id: M.id(), projectId: active.id, subject: text(fd, 'subject'), requirement: text(fd, 'requirement'), source: text(fd, 'source'), direction: text(fd, 'direction'), raisedBy: text(fd, 'raisedBy'), assignedTo: text(fd, 'assignedTo'), priority: text(fd, 'priority'), dueDate: text(fd, 'dueDate'), status: 'Open', reply: '', draft: '', verified: false }; await commit({ ...w, queries: [...w.queries, q] }); close(); })}><div className={s.formGrid}><Field label="Source" name="source" value="Customer" options={['Customer', 'Vendor', 'Internal']}/><Field label="Direction" name="direction" value="Incoming" options={['Incoming', 'Outgoing']}/><Field label="Subject" name="subject" required wide/><Field label="Query / requirement" name="requirement" required type="textarea" wide/><Field label="Raised by" name="raisedBy"/><Field label="Assigned to" name="assignedTo" value={active?.owner ?? ''}/><Field label="Priority" name="priority" value="Medium" options={M.PRIORITIES}/><Field label="Due date" name="dueDate" type="date"/></div>{actionButtons('Create Query')}</form>}
 {modal.kind === 'query-edit' && (() => { const q = queries.find(x => x.id === modal.queryId); if (!q)
            return <p>Query unavailable for active PID.</p>; return <form onInput={e => { const target=e.target as HTMLInputElement; if(target.name==='draft'){const form=e.currentTarget;const check=form.elements.namedItem('verified') as HTMLInputElement;check.checked=false;const status=form.elements.namedItem('status') as HTMLSelectElement;status.value='Pending verification';} }} onSubmit={e => save(e, async (fd) => { const draft = text(fd, 'draft'), reply = text(fd, 'reply'), verified = fd.get('verified') === 'on'; if (verified && !draft)
            throw Error('A non-empty draft must be reviewed before marking Ready to send'); const status = text(fd, 'status'); if (status === 'Ready to send' && !verified)
            throw Error('Verify the draft first'); await commit({ ...w, queries: w.queries.map(x => x.id === q.id ? { ...x, reply, draft, verified, status: verified ? 'Ready to send' : status } : x) }, 'Query saved; nothing sent'); close(); })}><h3>{q.subject}</h3><p>{q.requirement}</p><div className={s.formGrid}><Field label="Reply received" name="reply" value={q.reply} type="textarea" wide/><Field label="Draft response" name="draft" value={q.draft} type="textarea" wide/><Field label="Status" name="status" value={q.status} options={['Open', 'Reply received', 'Pending verification', 'Ready to send', 'Closed']}/><label className={s.check}><input type="checkbox" name="verified" defaultChecked={q.verified}/>I reviewed this exact draft for manual sending</label></div><p>Verification is local and records this saved draft. Editing it requires another review. Email automation is unavailable.</p>{actionButtons('Save Query')}</form>; })()}
 {modal.kind === 'suggestion' && <form onSubmit={e => save(e, async (fd) => { const title = text(fd, 'title'), description = text(fd, 'description'); if (!title || !description)
            throw Error('Title and description required'); const v: M.Suggestion = { id: M.id(), title, description, type: text(fd, 'type'), priority: text(fd, 'priority'), module: text(fd, 'module'), expected: text(fd, 'expected'), impact: text(fd, 'impact'), status: 'Pending Approval', createdAt: new Date().toISOString() }; await commit({ ...w, suggestions: [...w.suggestions, v] }); close(); })}><p>Submission does not authorize implementation until owner review.</p><div className={s.formGrid}><Field label="Suggestion title" name="title" required wide/><Field label="Request type" name="type" value="Improvement" options={['New Feature', 'Feature Not Working', 'Improvement', 'UI / UX', 'Report / Calculation', 'Security / Access', 'Other']}/><Field label="Priority" name="priority" value="Medium" options={M.PRIORITIES}/><Field label="Page / Module" name="module" wide/><Field label="Problem / Feature Description" name="description" type="textarea" required wide/><Field label="Expected Result" name="expected" type="textarea" wide/><Field label="Business Impact" name="impact" type="textarea" wide/></div><p>Status after submission: Pending Approval.</p>{actionButtons('Submit for Approval')}</form>}
 {modal.kind === 'custom' && <form onSubmit={e => save(e, async (fd) => { if (!active)
            throw Error('Select an active PID'); const request = text(fd, 'request'); if (!request)
            throw Error('Describe the task'); setNotice(`Local plan: ${request}. Scope: ${active.pid}, ${ready.length} Ready files; evidence required; missing inputs unresolved. AI execution is unavailable.`); close(); })}><p>Describe what you need in normal language. Original behavior uses Ready PID documents only. This copy can record a scope preview; it cannot run the private AI planner.</p><Field label="What do you want the agent to do?" name="request" type="textarea" required/><Field label="Output audience" name="audience" value="Internal" options={['Internal', 'Customer', 'Both']}/><p>Historical pricing is unavailable. Customer-only output must never receive internal rates, discounts or margins.</p>{actionButtons('Review Local Scope')}</form>}
 {modal.kind === 'archive' && active && <form onSubmit={e => save(e, async (fd) => { if (text(fd, 'confirmation') !== active.pid)
            throw Error('Type the exact PID to archive'); await commit({ ...w, projects: w.projects.map(p => p.id === active.id ? { ...p, archived: true } : p), activeId: '' }, 'PID archived locally; records retained for recovery'); close(); })}><p>Type {active.pid} to archive this local PID. All original files and reports remain recoverable. The original site exposes complete deletion; irreversible deletion is deliberately unavailable here.</p><Field label="Confirm PID" name="confirmation" required/>{actionButtons('Archive PID')}</form>}
 {modal.kind === 'document' && (() => { const d = docs.find(x => x.id === modal.documentId); return d ? <FilePreview doc={d}/> : <p>Document unavailable for active PID.</p>; })()}
 {modal.kind === 'reports' && selectedReport && <><p>{active?.pid} · {active?.name}</p><h3>{selectedReport.title}</h3><p>{selectedReport.status} · {selectedReport.createdAt}</p>{stale(selectedReport) && <p className={s.error}>STALE: Ready document revisions changed after this report was saved. Recalculate before relying on it.</p>}<label>Output audience<select aria-label="Report output audience" value={audience} onChange={e => setAudience(e.target.value as M.Audience)}>{(selectedReport.audience === 'Both' ? ['Internal', 'Customer'] : [selectedReport.audience]).map(a => <option key={a}>{a}</option>)}</select></label>{M.outputTables(selectedReport, audience).map((t, i) => <Table table={t} key={i}/>)}<section className={s.customBanner}><span className={s.eyebrow}>THIS REPORT ONLY · NO MIXED DATA</span><h3>{selectedReport.title} · Exact report downloads</h3><div className={s.actions}><button onClick={() => void act(() => downloadExcel(selectedReport, audience))}>Download This Excel</button><button onClick={() => downloadWord(selectedReport, audience)}>Download This Word</button></div></section><h3>Saved report history</h3>{reports.map(r => <button className={s.queryCard} key={r.id} onClick={() => { setAudience(r.audience === 'Both' ? 'Internal' : r.audience); setModal({ ...modal, reportId: r.id }); }}>{r.title}<small>{r.createdAt} · {r.audience}</small></button>)}</>}
 {modal.kind === 'task' && <><p>{M.TASKS[modal.task ?? 0][1]}. The workflow is scoped to {active?.pid ?? 'no selected PID'}.</p><section className={s.customBanner}><strong>Only this selected task will run</strong><p>Ready files: {ready.length}. Superseded files and other PIDs are excluded.</p><p>✓ Document and revision evidence · ✓ Missing inputs remain unresolved · ✓ Independent review required</p></section>{!active ? <p>Create or select a PID before running any workflow.</p> : modal.task === 0 ? <><p>Local intake registers original bytes, SHA256 and revision metadata. Document classification, OCR and canonical Phase 4C extraction are not connected.</p><button className={s.primary} disabled={busy} onClick={() => void act(() => saveReport('Document Intake & Register', [{ title: 'Document Register', headers: ['Filename', 'Revision', 'Status', 'Source', 'SHA256', 'Extraction'], rows: docs.map(d => [d.name, d.revision, d.status, d.source, d.sha256, 'Not extracted']) }], 'Internal'))}>Save Local Register Only →</button></> : modal.task === 7 ? <RateCalculator busy={busy} onSave={async (input, item, unit, evidence) => { const result = M.calculateRate(input); if (result.errors.length)
            throw Error(result.errors.join('; ')); await saveReport('Individual Rate Analysis', [{ title: 'Input Evidence', headers: ['Item', 'Quantity', 'UOM', 'Source', 'Verification'], rows: [[item, String(input.quantity ?? 'Not provided'), unit, evidence, 'Manual input — not independently verified']], confidential: true }, { title: 'Commercial Inputs', headers: ['Input', 'Value'], rows: [...M.RATE_FIELDS.map(k => [fieldLabels[k], String(input[k] ?? 'Not provided')]), ['Profit basis', input.profitBasis], ['Wastage basis', input.wastageBasis], ['Overhead basis', input.overheadBasis], ['Contingency basis', input.contingencyBasis]], confidential: true }, { title: 'Rate Calculation Method', headers: ['Cost Element', 'Result'], rows: Object.entries(result.values).map(([k, v]) => [k, M.money(v)]), confidential: true }, { title: 'QC', headers: ['Check', 'Status'], rows: [['Missing input count', String(result.missing.length)], ['Zero quantity', result.excluded ? 'Excluded from roll-up' : 'Active'], ['Final approval', 'Pending independent review and Owner approval']], confidential: true }], 'Internal', { item, unit, evidence, input }); }}/> : modal.task === 5 ? <QuantityCalculator busy={busy} onSave={async (tables) => saveReport('Quantity Reconciliation', tables, 'Internal')}/> : modal.task === 11 ? <><p>Local roll-up uses the latest saved rate per exact item name/UOM. This is a draft, with no automatic Bid approval.</p><button className={s.primary} disabled={busy} onClick={() => void act(async () => { const latest = new Map<string, M.Report>(); for (const r of reports)
            if (r.rate)
                latest.set(`${r.rate.item.toLowerCase()}|${r.rate.unit}`, r); const rows: string[][] = []; let total = 0, missing = 0; for (const r of latest.values()) {
            const n = M.calculateRate(r.rate!.input).values['BOQ amount'];
            if (n === null || stale(r))
                missing++;
            else
                total += n;
            rows.push([r.rate!.item, r.rate!.unit, M.money(n), stale(r) ? 'STALE' : n === null ? 'Not calculable' : 'Unverified manual input', r.id]);
        } await saveReport('Final Estimation & Bid QC', [{ title: 'Final Cost Roll-Up Status', headers: ['Item', 'UOM', 'BOQ Amount', 'QC Status', 'Report ID'], rows, confidential: true }, { title: 'Bid/No-Bid Recommendation', headers: ['Gate', 'Result'], rows: [['Total priced amount', missing || !latest.size ? 'Not calculable' : M.money(total)], ['Missing or stale lines', String(missing)], ['Output tax', 'Not provided — final tax-inclusive bid not calculable'], ['Technical compliance', 'Not independently verified'], ['Commercial approval', 'Pending Owner approval'], ['Final recommendation', 'HOLD — draft only']], confidential: true }, { title: 'Customer Summary', headers: ['Gate', 'Status'], rows: [['Scope and quantities', 'Pending independent verification'], ['Final bid release', 'HOLD — review required']] }], 'Both'); })}>Save Local Draft Roll-Up Only →</button></> : <><p className={s.error}>Backend not connected. The original workflow runs server-side AI over tender documents. Its prompts, extraction, ranking, finance and technical decisions cannot be reproduced from visible labels alone.</p><button disabled>Run Selected Task Only →</button><p>No findings or prices have been fabricated. Use the observable local intake, quantity and rate workflows; connect a reviewed backend to support this task.</p></>}</>}
 </Dialog>}
 </div>;
}
function RateCalculator({ onSave, busy }: {
    onSave: (i: M.RateInput, item: string, unit: string, evidence: string) => Promise<void>;
    busy: boolean;
}) {
    const [result, setResult] = useState<M.RateResult | null>(null), [input, setInput] = useState<M.RateInput | null>(null), [error, setError] = useState('');
    const ref = useRef<HTMLFormElement>(null);
    const read = () => { const fd = new FormData(ref.current!); const i = { ...Object.fromEntries(M.RATE_FIELDS.map(k => [k, number(fd, k)])), profitBasis: text(fd, 'profitBasis'), wastageBasis: text(fd, 'wastageBasis'), overheadBasis: text(fd, 'overheadBasis'), contingencyBasis: text(fd, 'contingencyBasis') } as M.RateInput; return { fd, i }; };
    return <form ref={ref} onInput={() => { setResult(null); setInput(null); }} onSubmit={e => { e.preventDefault(); const { i } = read(); setInput(i); setResult(M.calculateRate(i)); setError(''); }}><p>Enter explicit per-unit inputs. Use 0 only for a confirmed zero allowance. Blank remains Not provided. Percentage application bases require explicit selection.</p><div className={s.formGrid}><Field label="Individual rate item" name="item" required wide/><Field label="UOM" name="unit" required/><Field label="Source / approved basis" name="evidence" required/>{M.RATE_FIELDS.map(k => <Field key={k} label={fieldLabels[k]} name={k} type="number" min={0} max={['discount', 'recoverablePercent'].includes(k) ? 100 : undefined}/>)}<label>Profit basis<select name="profitBasis" required defaultValue=""><option value="" disabled>Select approved basis</option><option value="MARKUP">Markup on cost</option><option value="MARGIN">Margin on sales</option></select></label><label>Wastage base<select name="wastageBasis" required defaultValue=""><option value="" disabled>Select approved basis</option><option value="NET">Net purchase price</option><option value="LANDED">Landed pre-tax material</option></select></label><label>Overhead base<select name="overheadBasis" required defaultValue=""><option value="" disabled>Select approved basis</option><option value="DIRECT">Direct unit cost</option><option value="MATERIAL">Landed pre-tax material</option></select></label><label>Contingency base<select name="contingencyBasis" required defaultValue=""><option value="" disabled>Select approved basis</option><option value="DIRECT">Direct unit cost</option><option value="WITH_OVERHEAD">Direct plus overhead</option></select></label></div><button className={s.primary}>Calculate</button>{result && <><Table table={{ title: 'Live Rate Calculation', headers: ['Cost Element', 'Result'], rows: Object.entries(result.values).map(([k, v]) => [k, M.money(v)]) }}/>{result.errors.length > 0 && <p className={s.error}>{result.errors.join('; ')}</p>}<p>Missing inputs: {result.missing.join(', ') || 'None'}{result.excluded ? ' · Quantity zero: excluded from financial roll-up.' : ''}</p>{!result.errors.length && <button type="button" disabled={busy || !input} onClick={() => { const { fd, i } = read(); void onSave(i, text(fd, 'item'), text(fd, 'unit'), text(fd, 'evidence')).catch(e => setError(String(e))); }}>Save This Rate Report</button>}</>}{error && <p className={s.error}>{error}</p>}</form>;
}
function QuantityCalculator({ onSave, busy }: {
    onSave: (t: M.Table[]) => Promise<void>;
    busy: boolean;
}) {
    const [tables, setTables] = useState<M.Table[] | null>(null), [error, setError] = useState('');
    return <form onInput={() => setTables(null)} onSubmit={e => { e.preventDefault(); const fd = new FormData(e.currentTarget); try {
        const variance = M.quantityVariance(number(fd, 'baseline'), number(fd, 'boq'));
        const load = M.electricalLoad(number(fd, 'kw'), number(fd, 'pf'), number(fd, 'volts'));
        if (variance.status === 'Invalid quantity')
            throw Error(variance.status);
        setTables([{ title: 'Quantity Reconciliation', headers: ['Item', 'Basis A', 'Basis B', 'Difference', 'Variance %', 'UOM', 'Evidence', 'Status'], rows: [[text(fd, 'item'), String(number(fd, 'baseline') ?? 'Not provided'), String(number(fd, 'boq') ?? 'Not provided'), String(variance.difference ?? 'Not calculable'), String(variance.percent ?? 'Not calculable'), text(fd, 'unit'), text(fd, 'evidence'), variance.status]] }, { title: 'Load and Arithmetic Checks', headers: ['Check', 'Formula', 'Result', 'Evidence'], rows: [['Apparent load', 'kW / PF', String(load.kva ?? 'Not calculable'), text(fd, 'evidence')], ['Three-phase current', 'kW × 1000 / (√3 × voltage × PF)', String(load.amps ?? 'Not calculable'), text(fd, 'evidence')]] }]);
        setError('');
    }
    catch (e) {
        setError(String(e));
    } }}><div className={s.formGrid}><Field label="Item / System" name="item" required/><Field label="UOM" name="unit" required/><Field label="Evidence (document / sheet / row)" name="evidence" required wide/><Field label="Drawing / schedule quantity" name="baseline" type="number" min={0}/><Field label="BOQ quantity" name="boq" type="number" min={0}/><Field label="Optional load (kW)" name="kw" type="number" min={0}/><Field label="Power factor" name="pf" type="number" min={0} max={1}/><Field label="Line voltage (V)" name="volts" type="number" min={0}/></div><p>Difference = BOQ − baseline. Percentage = difference / baseline × 100. A zero baseline has no defined percentage.</p><button className={s.primary}>Calculate</button>{tables?.map(t => <Table key={t.title} table={t}/>)}{tables && <button type="button" disabled={busy} onClick={() => void onSave(tables).catch(e => setError(String(e)))}>Save This Quantity Report</button>}{error && <p className={s.error}>{error}</p>}</form>;
}
