'use client';
import {useState} from 'react';
import {sharedCost,type CoverageReviews,type CoverageCommand} from '../lib/master-audit-v2/pilot/coverage-review';
import {purchaseCoverage} from '../lib/master-audit-v2/pilot/purchase-coverage';
import type {PilotView,PilotDocument} from '../lib/master-audit-v2/pilot/view-model';
import type {BillCandidate} from '../lib/master-audit-v2/pilot/unlinked-bills';
import s from './pilot.module.css';
async function action(path:string,body:unknown){const response=await fetch('/api/master-audit-v2/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(85000)});const result=await response.json();if(!response.ok)throw Error(result.error??'Action failed');return result;}
export default function CoverageReviewPanel({data,soId,initial,busy,onOpen,onSaved}:{data:PilotView;soId:string;initial:CoverageReviews;onSaved:(r:CoverageReviews)=>void;busy:boolean;onOpen:(d:PilotDocument)=>void}){
 const reviews=initial;const [working,setWorking]=useState(false),[message,setMessage]=useState('');
 const coverage=purchaseCoverage(data,soId),[billId,setBillId]=useState(coverage.bills[0]?.id??''),[poId,setPoId]=useState(coverage.pos[0]?.id??''),[status,setStatus]=useState<'INTERIM'|'FINAL'|'UNKNOWN'>('UNKNOWN'),[note,setNote]=useState(''),[amounts,setAmounts]=useState<Record<string,string>>({}),[allocationNote,setAllocationNote]=useState('');
 const [result,setResult]=useState<{candidates:BillCandidate[];snapshot:string;pages:number;complete:boolean;issue:string;poId:string}|null>(null);
 const [sharedId,setSharedId]=useState(coverage.shared[0]?.id??'');const sharedPO=coverage.shared.find(p=>p.id===sharedId);let cost:ReturnType<typeof sharedCost>|null=null,blocked='';
 if(sharedPO)try{cost=sharedCost(data,soId,sharedPO.id);}catch(e){blocked=e instanceof Error?e.message:'Allocation needs review';}
 const prior=reviews['BILL:'+billId],allocation=sharedPO?reviews['PO:'+sharedPO.id]:undefined,disabled=busy||working;
 async function save(input:CoverageCommand){if(disabled)return;setWorking(true);setMessage('Saving review…');try{const r=await action('coverage-review',input);onSaved(r.reviews);setMessage('Review saved. GP approval and final project cost remain separate.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed. Reload before retrying.');}finally{setWorking(false);}}
 async function search(){if(disabled||!poId)return;setWorking(true);setResult(null);setMessage('Searching this PO vendor’s Bills…');try{const r=await action('unlinked-bills',{soId,poId,snapshot:data.snapshotId});setResult(r);setMessage(r.issue?'Search partial: '+r.issue:'Vendor search finished. Candidates require document evidence.');}catch(e){setMessage(e instanceof Error?e.message:'Search failed. Reload before retrying.');}finally{setWorking(false);}}
 return <section className={s.panel} aria-label="Coverage review workspace"><h2>Coverage review</h2><p>Interim/Final એ Bill અંગેનો Ownerનો નિર્ણય છે. Final Bill status આખા projectનો ખર્ચ પૂર્ણ હોવાની ખાતરી નથી. Source બદલાય ત્યારે ફરી review જરૂરી છે.</p><p role="status">{message}</p>
 <h3>Bill settlement status</h3><div className={s.cards}>{(['INTERIM','FINAL','UNKNOWN'] as const).map(label=><article key={label}><span>{label==='UNKNOWN'?'Unknown / review again':label==='INTERIM'?'Interim Bills':'Final Bills'}</span><b>{coverage.bills.filter(b=>{const r=reviews[b.key];return (r&&r.snapshot===data.snapshotId?r.status:'UNKNOWN')===label;}).length}</b></article>)}</div><div className={s.tableWrap}><table><thead><tr><th>Bill</th><th>Saved status</th><th>Evidence note</th></tr></thead><tbody>{coverage.bills.map(b=>{const r=reviews[b.key];return <tr key={b.key}><td><button className={s.linkButton} onClick={()=>{setBillId(b.id);setStatus(r&&r.status!=='ALLOCATED'?r.status:'UNKNOWN');setNote(r?.note??'');}}>{b.number}</button><button className={s.linkButton} onClick={()=>onOpen(b)}>Open</button></td><td>{r?(r.snapshot===data.snapshotId?r.status:'Review again — '+r.status):'Unknown'}</td><td>{r?.note??'No settlement evidence recorded'}</td></tr>;})}</tbody></table></div>
 <div className={s.controls}><label>Bill to review<select value={billId} disabled={disabled} onChange={e=>{setBillId(e.target.value);const r=reviews['BILL:'+e.target.value];setStatus(r&&r.status!=='ALLOCATED'?r.status:'UNKNOWN');setNote(r?.note??'');}}>{coverage.bills.map(b=><option key={b.id} value={b.id}>{b.number}</option>)}</select></label><label>Settlement status<select value={status} disabled={disabled} onChange={e=>setStatus(e.target.value as typeof status)}><option value="UNKNOWN">Unknown / needs review</option><option value="INTERIM">Interim</option><option value="FINAL">Final</option></select></label><label>Settlement evidence note<input value={note} maxLength={1000} disabled={disabled} onChange={e=>setNote(e.target.value)} placeholder="Owner / vendor confirmation and date"/></label><button className={s.linkButton} disabled={disabled||!billId||!note.trim()} onClick={()=>save({soId,documentId:billId,kind:'BILL',snapshot:data.snapshotId,revision:prior?.revision??0,status,note,amounts:{}})}>Save Bill status</button></div>
 <h3>Find unlinked vendor Bills</h3><p>પસંદ કરેલા POના vendorના FY 2026–27 Bills તપાસો. આ SOના saved PO referencesમાં ન હોય તેવા Bills candidates તરીકે દેખાશે. Vendor match માત્રથી SO link સાબિત થતી નથી. અન્ય vendorsના direct purchases આ શોધમાં આવતાં નથી.</p><div className={s.controls}><label>Vendor from Purchase Order<select value={poId} disabled={disabled} onChange={e=>{setPoId(e.target.value);setResult(null);}}>{coverage.pos.map(p=><option key={p.id} value={p.id}>{p.number}</option>)}</select></label><button className={s.linkButton} disabled={disabled||!poId} onClick={search}>Search vendor Bills</button></div>
 {result&&<><p>{result.snapshot!==data.snapshotId?'Source changed — search again.':`${result.candidates.length} candidates · ${result.pages} pages · ${result.complete?'Vendor list finished':'Partial search'}`} Coverage is not confirmed.</p><div className={s.tableWrap}><table><thead><tr><th>Bill</th><th>Vendor</th><th>Date</th><th>Reference</th><th>Source status</th><th>Review</th></tr></thead><tbody>{result.candidates.map(b=><tr key={b.id}><td>{b.number}<small>{b.id}</small></td><td>{b.vendor}</td><td>{b.date}</td><td>{b.reference||'No reference'}</td><td>{b.status}</td><td>{b.linkedElsewhere?'Referenced by another saved PO':'SO link not established'}</td></tr>)}</tbody></table></div></>}
 <h3>Shared PO cost allocation</h3>{coverage.shared.length>0&&<div className={s.controls}><label>Shared Purchase Order<select value={sharedId} disabled={disabled} onChange={e=>{setSharedId(e.target.value);setAmounts({});setAllocationNote('');}}>{coverage.shared.map(p=><option value={p.id} key={p.id}>{p.number}</option>)}</select></label></div>}<p>ફક્ત captured Billsના GST-exclusive ખર્ચની ફાળવણી કરો. PO commitment કે અંદાજિત બાકી ખર્ચ ઉમેરાતો નથી. Saved allocation અલગ review record છે; GP verification આપમેળે થતું નથી.</p>
 {!sharedPO?<p>No shared POs for this SO.</p>:<><p>{sharedPO.number}: {blocked||`${cost?.currency} ${cost?.total} captured Bill subtotal to allocate`}</p>{allocation&&<p>Saved allocation: {allocation.snapshot===data.snapshotId?'Current':'Source changed — review again'} · {Object.entries(allocation.amounts).map(([so,n])=>`${so}: ${n}`).join(' · ')} · {allocation.note}</p>}{cost&&<><div className={s.controls}>{cost.owners.map(owner=><label key={owner}>{owner} allocated amount<input inputMode="decimal" aria-label={owner+' allocated amount'} disabled={disabled} value={amounts[owner]??''} onChange={e=>setAmounts({...amounts,[owner]:e.target.value})}/></label>)}<label>Allocation evidence note<input maxLength={1000} value={allocationNote} disabled={disabled} onChange={e=>setAllocationNote(e.target.value)}/></label><button className={s.linkButton} disabled={disabled||!allocationNote.trim()||cost.owners.some(o=>!amounts[o])} onClick={()=>save({soId,documentId:sharedPO.id,kind:'PO',snapshot:data.snapshotId,revision:allocation?.revision??0,status:'ALLOCATED',note:allocationNote,amounts})}>Save cost allocation</button></div><p>દરેક SOનો ભાગ evidence મુજબ લખો; કુલ રકમ ઉપરની captured Bill subtotal જેટલી જ હોવી જોઈએ.</p></>}</>}
 </section>;
}
