'use client';
import type {ReactNode} from 'react';
import type {PilotDocument,PilotView} from '../lib/master-audit-v2/pilot/view-model';
import {purchaseCoverage} from '../lib/master-audit-v2/pilot/purchase-coverage';
import s from './pilot.module.css';
export default function PurchaseCoveragePanel({data,soId,busy,refreshing,onRefresh,onDiscover,onStop,onOpen,syncButton}:{data:PilotView;soId:string;busy:boolean;refreshing:boolean;onRefresh:()=>void;onDiscover:()=>void;onStop:()=>void;onOpen:(d:PilotDocument)=>void;syncButton:(d:PilotDocument)=>ReactNode}){
 const coverage=purchaseCoverage(data,soId),so=data.documents.find(d=>d.type==='SO'&&d.id===soId)!;
 return <section className={s.panel} aria-label={'Purchase coverage for '+so.number}>
  <h2>{so.number} — Purchase / Bill coverage</h2>
  <p>Saved records પરથી આ તપાસ આપમેળે થાય છે. Sync પછી પરિણામ ફરી ગણાય છે.</p>
  <button className={s.linkButton} disabled={busy} onClick={onRefresh}>↻ Refresh saved documents</button>
  <button className={s.linkButton} disabled={busy} onClick={onDiscover}>Find linked documents</button>
  {refreshing&&<button className={s.linkButton} onClick={onStop}>Stop after current document</button>}
  <p>આ SO, saved POs, linked saved Bills અને Invoice candidates refresh થશે. નવા POs, missing linked Bills અને Invoice candidates માટે Find linked documents વાપરો. આ bounded search છે; સંપૂર્ણ project coverageની ખાતરી નથી.</p>
  <div className={s.cards}><article><span>Saved POs</span><b>{coverage.pos.length}</b></article><article><span>Saved referenced Bills</span><b>{coverage.bills.length}</b><small>Shared references may be included</small></article><article><span>POs without Bill references</span><b>{coverage.withoutBills.length}</b></article><article><span>Missing Bill details</span><b>{coverage.missingBillIds.length}</b></article></div>
  <p className={s.notice}><strong>Final cost coverage: Not confirmed.</strong> Interim Bills, unlinked purchases, final settlement અને અન્ય ખર્ચની તપાસ બાકી હોઈ શકે છે. Captured Billsનો GP final margin નથી. PO અને Billનો તફાવત ખર્ચમાં ઉમેરાતો નથી.</p>
  {coverage.shared.length>0&&<p role="note">Shared PO allocation needed: {coverage.shared.map(p=>p.number).join(', ')}. Shared cost આ SOમાં આપમેળે ફાળવાતો નથી.</p>}
  <details className={s.technical}><summary>PO / Bill reference checks ({coverage.pos.length} POs)</summary><div className={s.tableWrap}><table><thead><tr><th>Purchase Order</th><th>Bill references</th><th>Check</th><th>Refresh</th></tr></thead><tbody>{coverage.pos.map(po=><tr key={po.key}><td><button className={s.linkButton} onClick={()=>onOpen(po)}>{po.number}</button></td><td>{[...new Set(po.billIds)].map(id=>{const bill=coverage.bills.find(b=>b.id===id);return <div key={id}>{bill?<button className={s.linkButton} onClick={()=>onOpen(bill)}>{bill.number}</button>:<>Missing Bill detail: {id}</>}</div>;})}{!po.billIds.length&&'No Bill reference — cost unknown'}</td><td>{coverage.shared.includes(po)?'Shared ownership — allocation pending':po.billIds.some(id=>coverage.missingBillIds.includes(id))?'Missing Bill detail':!po.billIds.length?'Coverage incomplete':'Saved references present — final cost unconfirmed'}</td><td>{syncButton(po)}</td></tr>)}</tbody></table></div></details>
  <details className={s.technical}><summary>Linked item rate differences ({coverage.rateDifferences.length})</summary><p>એક જ linked PO itemનો unit rate સરખાવેલો છે; GST excluded. Rate difference ભૂલ અથવા બાકી payableનો પુરાવો નથી. Interim Bill માટે rate અલગ હોઈ શકે છે.</p><div className={s.tableWrap}><table><thead><tr><th>PO → Bill</th><th>Item</th><th>PO unit rate</th><th>Bill unit rate</th><th>Refresh Bill</th></tr></thead><tbody>{coverage.rateDifferences.map(r=><tr key={r.po.key+':'+r.poLineId+':'+r.bill.key+':'+r.billLineId}><td><button className={s.linkButton} onClick={()=>onOpen(r.po)}>{r.po.number}</button> → <button className={s.linkButton} onClick={()=>onOpen(r.bill)}>{r.bill.number}</button></td><td>{r.item}</td><td>{r.po.currency} {r.poRate}</td><td>{r.bill.currency} {r.billRate}</td><td>{syncButton(r.bill)}</td></tr>)}</tbody></table></div>{!coverage.rateDifferences.length&&<p>No differences found among comparable saved lines.</p>}{coverage.uncheckedLines>0&&<p>{coverage.uncheckedLines} Bill lines could not be compared reliably: line link, shared ownership, unit, currency or tax basis needs review.</p>}</details>
 </section>;
}
