import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { setTimeout as sleep } from 'node:timers/promises';
import { Store } from '../src/store.ts';
import { runTask } from '../src/engine.ts';
import type { Providers } from '../src/engine.ts';
function fixture(){const dir=mkdtempSync(path.join(os.tmpdir(),'standalone-orchestrator-')),store=new Store(path.join(dir,'test.db'));return{store,close:()=>{store.db.close();rmSync(dir,{recursive:true})}}}
async function until(fn:()=>boolean){for(let i=0;i<200;i++){if(fn())return;await sleep(10)}throw Error('timeout')}
const fake:Providers={plan:async()=>({prompt:'safe task',risk:'LOW',reason:'test'}),execute:async()=> 'tests passed',review:async()=>({verdict:'DONE',summary:'complete',nextPrompt:''})};
test('validation, stale decisions, UNTOUCH and rejection',()=>{const f=fixture(),s=f.store;try{assert.throws(()=>s.create('',true,3));const t=s.create('test',false,2);s.claim();const a=s.gate(t.id,'PLAN','scope');s.decide(t.id,a.id,'UNTOUCH');assert.equal(s.pending(t.id)?.id,a.id);assert.throws(()=>s.decide(t.id,'stale','ACCEPT'));s.decide(t.id,a.id,'REJECT');assert.equal(s.get(t.id).state,'REJECTED')}finally{f.close()}});
test('plan and tool approval gates prevent early execution',async()=>{const f=fixture(),s=f.store;let started=false,ran=false;try{const t=s.create('test',false,2),running=runTask(s,s.claim()!,{...fake,execute:async(_t,approve)=>{started=true;await approve('run_command',{CommandLine:'example'});ran=true;return 'done'}});await until(()=>!!s.pending(t.id));assert.equal(started,false);s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await until(()=>s.pending(t.id)?.kind==='TOOL');assert.equal(ran,false);s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await until(()=>s.pending(t.id)?.kind==='REVIEW');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(ran,true);assert.equal(s.get(t.id).state,'COMPLETED')}finally{f.close()}});
test('interrupted active work fails closed while queued work stays queued',()=>{const f=fixture(),s=f.store;try{const active=s.create('active',true,1);s.claim();s.gate(active.id,'PLAN','x');const queued=s.create('queued',true,1);s.recover();assert.equal(s.get(active.id).state,'FAILED');assert.equal(s.get(queued.id).state,'QUEUED');assert.equal(s.pending(active.id),null)}finally{f.close()}});
test('ACCEPT_ALL auto-approves later project-scoped read-only tools only',async()=>{const f=fixture(),s=f.store,old=process.env.ORCHESTRATOR_PROJECT_DIR;process.env.ORCHESTRATOR_PROJECT_DIR=os.tmpdir();let calls=0;try{const t=s.create('inspect',false,1),running=runTask(s,s.claim()!,{...fake,execute:async(_t,approve)=>{await approve('view_file',{AbsolutePath:path.join(os.tmpdir(),'package.json')});calls++;await approve('view_file',{AbsolutePath:path.join(os.tmpdir(),'README.md')});calls++;return 'done'}});await until(()=>s.pending(t.id)?.kind==='PLAN');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await until(()=>s.pending(t.id)?.kind==='TOOL');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT_ALL');await until(()=>s.pending(t.id)?.kind==='REVIEW');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(calls,2);assert.equal(s.get(t.id).acceptAllReadOnly,true);assert.equal(s.history(t.id).filter((e:any)=>e.kind==='AUTO_ACCEPT').length,1);assert.equal(s.get(t.id).state,'COMPLETED')}finally{if(old===undefined)delete process.env.ORCHESTRATOR_PROJECT_DIR;else process.env.ORCHESTRATOR_PROJECT_DIR=old;f.close()}});

test('single approval mode gates plan once then skips safe tool and normal review gates',async()=>{const f=fixture(),s=f.store,old=process.env.ORCHESTRATOR_PROJECT_DIR;process.env.ORCHESTRATOR_PROJECT_DIR=os.tmpdir();try{const t=s.create('auto inspect',true,1),running=runTask(s,s.claim()!,{...fake,execute:async(_t,approve)=>{assert.equal(await approve('view_file',{AbsolutePath:path.join(os.tmpdir(),'package.json')}),true);return 'done'}});await until(()=>s.pending(t.id)?.kind==='PLAN');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(s.pending(t.id),null);assert.equal(s.get(t.id).state,'COMPLETED');assert.equal(s.history(t.id).filter((e:any)=>e.kind==='AUTO_ACCEPT').length,1)}finally{if(old===undefined)delete process.env.ORCHESTRATOR_PROJECT_DIR;else process.env.ORCHESTRATOR_PROJECT_DIR=old;f.close()}});

test('API key vault persists encrypted values and rejects a different owner token',async()=>{const { readFileSync,statSync }=await import('node:fs'),{ SecretsVault }=await import('../src/secrets.ts');const dir=mkdtempSync(path.join(os.tmpdir(),'orchestrator-vault-')),file=path.join(dir,'keys.enc');try{const vault=new SecretsVault('owner-token-at-least-twenty-characters',file),keys={openai:'openai-secret-value',gemini:'gemini-secret-value',claude:'claude-secret-value'};vault.save(keys);const raw=readFileSync(file,'utf8');assert.equal(raw.includes('openai-secret-value'),false);assert.deepEqual(vault.load(),keys);assert.throws(()=>new SecretsVault('different-owner-token-twenty-chars',file).load());assert.equal(statSync(file).mode&0o777,0o600)}finally{rmSync(dir,{recursive:true})}});

test('unattended mode auto-approves project commands and later plans',async()=>{const f=fixture(),s=f.store,old=process.env.ORCHESTRATOR_PROJECT_DIR;process.env.ORCHESTRATOR_PROJECT_DIR=os.tmpdir();let plans=0,reviews=0;try{const t=s.create('unattended',true,1),running=runTask(s,s.claim()!,{plan:async()=>({prompt:`plan ${++plans}`,risk:'LOW',reason:'test'}),execute:async(_t,approve)=>{assert.equal(await approve('run_command',{CommandLine:'npm test',Cwd:os.tmpdir()}),true);return 'done'},review:async()=>++reviews===1?{verdict:'CONTINUE',summary:'continue',nextPrompt:'next'}:{verdict:'DONE',summary:'done',nextPrompt:''}});await until(()=>s.pending(t.id)?.kind==='PLAN');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(s.pending(t.id),null);assert.equal(s.get(t.id).state,'COMPLETED');assert.equal(s.get(t.id).round,2);assert.equal(s.get(t.id).maxRounds,2);assert.ok(s.history(t.id).filter((e:any)=>e.kind==='AUTO_ACCEPT').length>=3);assert.equal(s.history(t.id).filter((e:any)=>e.kind==='AUTO_EXTEND').length,1)}finally{if(old===undefined)delete process.env.ORCHESTRATOR_PROJECT_DIR;else process.env.ORCHESTRATOR_PROJECT_DIR=old;f.close()}});

test('accepted high-risk HUMAN review continues with next prompt instead of completing',async()=>{const f=fixture(),s=f.store;let reviews=0;try{const t=s.create('needs evidence',true,5),running=runTask(s,s.claim()!,{plan:async()=>({prompt:'inspect evidence',risk:'HIGH',reason:'test'}),execute:async()=> 'report',review:async()=>++reviews===1?{verdict:'HUMAN',summary:'evidence conflict',nextPrompt:'collect exact evidence'}:{verdict:'DONE',summary:'verified',nextPrompt:''}});await until(()=>s.pending(t.id)?.kind==='PLAN');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await until(()=>s.pending(t.id)?.kind==='REVIEW');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(s.get(t.id).state,'COMPLETED');assert.equal(s.get(t.id).round,2);assert.equal(reviews,2)}finally{f.close()}});

test('only terminal tasks can be deleted with their audit history',()=>{const f=fixture(),s=f.store;try{const active=s.create('active',true,1);assert.throws(()=>s.remove(active.id));s.claim();s.fail(active.id,'test failure');assert.ok(s.history(active.id).length>0);s.remove(active.id);assert.throws(()=>s.get(active.id));assert.equal(s.history(active.id).length,0)}finally{f.close()}});

test('unattended low-risk HUMAN review auto-continues when next prompt is concrete',async()=>{const f=fixture(),s=f.store;let reviews=0;try{const t=s.create('repeat evidence checks',true,5),running=runTask(s,s.claim()!,{plan:async()=>({prompt:'inspect evidence',risk:'LOW',reason:'read only'}),execute:async()=> 'report',review:async()=>++reviews===1?{verdict:'HUMAN',summary:'resolve evidence gap',nextPrompt:'inspect the source record'}:{verdict:'DONE',summary:'verified',nextPrompt:''}});await until(()=>s.pending(t.id)?.kind==='PLAN');s.decide(t.id,s.pending(t.id)!.id,'ACCEPT');await running;assert.equal(s.pending(t.id),null);assert.equal(s.get(t.id).state,'COMPLETED');assert.equal(s.get(t.id).round,2);assert.equal(s.history(t.id).filter((e:any)=>e.kind==='AUTO_CONTINUE_HUMAN').length,1)}finally{f.close()}});

test('task can pause, resume without losing round, and stop',()=>{const f=fixture(),s=f.store;try{const t=s.create('controlled work',true,5);s.claim();assert.equal(s.pause(t.id).state,'PAUSED');assert.equal(s.resume(t.id).state,'QUEUED');assert.equal(s.claim()!.round,1);assert.equal(s.stop(t.id).state,'REJECTED')}finally{f.close()}});
