'use client';
import { useEffect,useState } from 'react';
type Policy={revision:number;enabled:Record<string,boolean>;updatedAt:string|null};
type Connector={id:string;name:string;available:boolean;permissions:string};
export default function ConnectionControls(){
  const [data,setData]=useState<{policy:Policy;connectors:Connector[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){try{const r=await fetch('/api/connections',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(String(e));}}
  useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),10000);return()=>clearInterval(id);},[]);
  async function change(action:string,id=''){
    if(!data)return;setBusy(true);setError('');
    try{const r=await fetch('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,revision:data.policy.revision})}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(String(e));}finally{setBusy(false);}
  }
  return <section aria-label="External connection controls"><h2>External Connections & Permissions</h2><p>Connect allows this app to use existing credentials. It does not authenticate or grant new provider scopes. Disconnect blocks this app’s requests; saved credentials and provider consent remain until separately revoked.</p><p><strong>Zoho WRITE = 0.</strong> Local reports and saved files continue working while external access is disconnected. These controls apply to this local application, not to Codex plugins or other apps.</p>{error&&<p role="alert" style={{color:'#a52626'}}>{error}</p>}<button disabled={busy||!data} onClick={()=>void change('disconnect-all')}>Disconnect All External Access</button><button disabled={busy} onClick={()=>void refresh()}>Refresh connection status</button>{!data?<p>Loading connection policy…</p>:data.connectors.map(c=><article key={c.id} style={{border:'1px solid #dbe5ef',borderRadius:12,padding:18,marginTop:12}}><h3>{c.name}</h3><p>{c.permissions}</p><p><strong>{!c.available?'Not implemented':data.policy.enabled[c.id]?'App access allowed — provider login not verified':'Disconnected — app requests blocked'}</strong></p><button disabled={busy||!c.available||data.policy.enabled[c.id]} onClick={()=>void change('connect',c.id)}>Connect {c.name}</button><button disabled={busy||!data.policy.enabled[c.id]} onClick={()=>void change('disconnect',c.id)}>Disconnect {c.name}</button>{c.id==='zoho'&&data.policy.enabled.zoho&&<p><a href="/api/zoho/connect">Authorize Zoho with existing approved READ scopes</a></p>}{!c.available&&<p>A reviewed server connector is required before Connect can be enabled.</p>}</article>)}<p>Local administrator controls: changes require the localhost application and a same-origin request. Shared-user owner authentication is not implemented. Requests already delivered to a provider cannot be recalled.</p></section>;
}
