import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {appendCoverageReview,coverageReviews,saveCoverageReview,readCoverageReviews} from '../pilot/coverage-review-store.ts';
import {sharedCost,type CoverageCommand} from '../pilot/coverage-review.ts';
import {handleCoverageReview} from '../pilot/coverage-review-http.ts';
import {openPilotStore} from '../pilot/store.ts';import {readPilotView} from '../pilot/view-model.ts';
import {findUnlinkedBills} from '../pilot/unlinked-bills.ts';import {handleUnlinkedBills} from '../pilot/unlinked-bills-http.ts';
function fixture(){const root=mkdtempSync(join(tmpdir(),'v2-coverage-'));const store=openPilotStore(root),run=store.start('123');
 for(const [module,singular,fields] of [
 ['salesorders','salesorder',{salesorder_id:'1',salesorder_number:'SO-2627009'}],
 ['purchaseorders','purchaseorder',{purchaseorder_id:'2',purchaseorder_number:'PO-2',vendor_id:'88',custom_fields:[{label:'Sales Order No',value:'SO-2627009 & SO-2627071'}],bills:[{bill_id:'3'}]}],
 ['bills','bill',{bill_id:'3',bill_number:'B-3',vendor_id:'88',sub_total:100.10}],
 ] as const){store.capture(run,'/books/v3/'+module+'/'+(fields as any)[singular+'_id'],JSON.stringify({code:0,[singular]:{date:'2026-05-01',currency_code:'INR',is_inclusive_tax:false,line_items:[{line_item_id:singular,quantity:1}],...fields}}));}store.publishCapturedDetails();store.close();return root;}
function command(snapshot:string):CoverageCommand{return {soId:'1',documentId:'3',kind:'BILL',snapshot,revision:0,status:'INTERIM',note:'Owner confirmed interim on 29 September',amounts:{}};}
test('Bill review persists without changing source or GP approvals; stale/concurrent edits fail and history is immutable',()=>{const root=fixture();try{const data=readPilotView(root),input=command(data.snapshotId),r=saveCoverageReview(root,input,'private-session');assert.equal(readCoverageReviews(root)['BILL:3'].status,'INTERIM');assert.equal(readPilotView(root).snapshotId,data.snapshotId);assert.throws(()=>saveCoverageReview(root,input,'owner'),/Another review/);assert.throws(()=>saveCoverageReview(root,{...input,snapshot:'b'.repeat(20)},'owner'),/Source changed/);const next=saveCoverageReview(root,{...input,revision:r['BILL:3'].revision,status:'FINAL'},'owner');assert.equal(next['BILL:3'].status,'FINAL');const db=new DatabaseSync(join(root,'data/master-audit-v2/db/master-audit-v2.sqlite'));try{assert.equal(db.prepare('SELECT count(*) n FROM v2_coverage_reviews').get()?.n,2);assert.notEqual(db.prepare('SELECT actor_hash FROM v2_coverage_reviews LIMIT 1').get()?.actor_hash,'private-session');for(const sql of ['DELETE FROM v2_coverage_reviews',"UPDATE v2_coverage_reviews SET status='FINAL'",'INSERT OR REPLACE INTO v2_coverage_reviews SELECT * FROM v2_coverage_reviews WHERE seq=1'])assert.throws(()=>db.exec(sql),/APPEND_ONLY/);assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name='v2_owner_verifications'").get(),undefined);}finally{db.close();}}finally{rmSync(root,{recursive:true});}});
test('exact allocation includes outside-pilot owner and rejects mismatch, negative, missing owner and reused Bill',()=>{const root=fixture();try{const data=readPilotView(root),db=new DatabaseSync(':memory:');try{assert.equal(sharedCost(data,'1','2').total,'100.1');const input:CoverageCommand={...command(data.snapshotId),kind:'PO',documentId:'2',status:'ALLOCATED',amounts:{'SO-2627009':'60.05','SO-2627071':'40.05'}};assert.equal(appendCoverageReview(db,data,input,'owner')['PO:2'].status,'ALLOCATED');for(const amounts of [{'SO-2627009':'100.10'},{'SO-2627009':'60.04','SO-2627071':'40.05'},{'SO-2627009':'-1','SO-2627071':'101.10'}])assert.throws(()=>appendCoverageReview(db,data,{...input,revision:1,amounts} as CoverageCommand,'owner'));data.documents.push({...data.documents[1],id:'9',key:'PO:9'});assert.throws(()=>sharedCost(data,'1','2'),/another PO/);}finally{db.close();}}finally{rmSync(root,{recursive:true});}});
test('unknown bills, nonpilot SO, empty evidence and injected Bill allocations cannot be saved',()=>{const root=fixture();try{const data=readPilotView(root),db=new DatabaseSync(':memory:');try{for(const extra of [{documentId:'9'},{soId:'9'},{note:''},{amounts:{'SO-2627009':'1'}},{status:'ALLOCATED'}])assert.throws(()=>appendCoverageReview(db,data,{...command(data.snapshotId),...extra} as CoverageCommand,'owner'));assert.deepEqual(coverageReviews(db),{});}finally{db.close();}}finally{rmSync(root,{recursive:true});}});
test('review HTTP enforces owner, local development, origin, strict body and revision',async()=>{let writes=0;const deps={environment:'development',owner:async()=> 'owner',save:()=>{writes++;return {};}};const req=(body:any=command('a'.repeat(20)),origin='http://localhost:3000')=>new Request('http://localhost:3000/api/master-audit-v2/coverage-review',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await handleCoverageReview(req(),{...deps,environment:'production'})).status,403);assert.equal((await handleCoverageReview(req(),{...deps,owner:async()=>null})).status,401);assert.equal((await handleCoverageReview(req(undefined,'https://evil.example'),deps)).status,403);assert.equal((await handleCoverageReview(req({...command('a'.repeat(20)),injected:true}),deps)).status,400);assert.equal(writes,0);assert.equal((await handleCoverageReview(req(),deps)).status,200);assert.equal(writes,1);});
const bill=(id:string,extra:any={})=>({bill_id:id,vendor_id:'88',bill_number:'B-'+id,date:'2026-05-02',vendor_name:'Vendor',...extra});
test('vendor discovery follows pages, excludes linked and out-of-FY Bills, never publishes candidates',async()=>{const root=fixture();try{const before=readPilotView(root),seen:string[]=[];const result=await findUnlinkedBills(root,{soId:'1',poId:'2',snapshot:before.snapshotId},async(_org,path)=>{seen.push(path);const page=seen.length;return {raw:JSON.stringify({code:0,bills:page===1?[bill('3'),bill('4'),bill('5',{date:'2025-04-01'})]:[bill('4'),bill('6')],page_context:{page,has_more_page:page===1}})};});assert.equal(result.complete,true);assert.deepEqual(result.candidates.map(b=>b.id),['4','6']);assert.ok(seen.every(p=>p.includes('vendor_id=88')));assert.equal(readPilotView(root).snapshotId,before.snapshotId);assert.equal(readPilotView(root).documents.length,3);}finally{rmSync(root,{recursive:true});}});
test('untrusted vendor result, stale source, stalled page and budget stay incomplete',async()=>{const root=fixture();try{const data=readPilotView(root),input={soId:'1',poId:'2',snapshot:data.snapshotId};let calls=0;await assert.rejects(findUnlinkedBills(root,{...input,snapshot:'c'.repeat(20)},async()=>{calls++;return {raw:''};}));assert.equal(calls,0);const r=await findUnlinkedBills(root,input,async()=>({raw:JSON.stringify({code:0,bills:[bill('4',{vendor_id:'99'})],page_context:{page:1,has_more_page:false}})}));assert.equal(r.complete,false);assert.equal(r.candidates.length,0);assert.match(r.issue,/filter/);let page=0;const stalled=await findUnlinkedBills(root,input,async()=>({raw:JSON.stringify({code:0,bills:[bill('4')],page_context:{page:++page,has_more_page:true}})}));assert.equal(stalled.pages,2);assert.equal(stalled.complete,false);let time=0;const timed=await findUnlinkedBills(root,input,async()=>{throw Error('should not run');},()=>time++?60001:0);assert.equal(timed.pages,0);assert.equal(timed.complete,false);}finally{rmSync(root,{recursive:true});}});
test('unlinked HTTP does not accept arbitrary vendor or endpoint',async()=>{let calls=0;const deps={environment:'development',owner:async()=>true,discover:async()=>{calls++;return {};}};const input={soId:'1',poId:'2',snapshot:'a'.repeat(20)};const req=(body:any)=>new Request('http://localhost:3000/api/master-audit-v2/unlinked-bills',{method:'POST',headers:{origin:'http://localhost:3000','Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await handleUnlinkedBills(req({...input,vendorId:'9'}),deps)).status,400);assert.equal(calls,0);assert.equal((await handleUnlinkedBills(req(input),deps)).status,200);});
test('vendor search is capped at five pages and concurrent searches do not acquire',async()=>{const root=fixture();try{const data=readPilotView(root),input={soId:'1',poId:'2',snapshot:data.snapshotId};let page=0;const r=await findUnlinkedBills(root,input,async()=>({raw:JSON.stringify({code:0,bills:[bill(String(100+page))],page_context:{page:++page,has_more_page:true}})}));assert.equal(r.pages,5);assert.equal(r.complete,false);let release!:(v:{raw:string})=>void;const pending=findUnlinkedBills(root,input,()=>new Promise(resolve=>{release=resolve;}));await assert.rejects(findUnlinkedBills(root,input,async()=>{throw Error('must not run');}),/already running/);release({raw:JSON.stringify({code:0,bills:[],page_context:{page:1,has_more_page:false}})});await pending;}finally{rmSync(root,{recursive:true});}});
import {createPilotClient} from '../pilot/client.ts';
test('vendor query is restricted to numeric vendor IDs on the Bill GET endpoint',async()=>{const client=createPilotClient({accessToken:'fixture',expiresAt:Date.now()+600000,apiDomain:'https://www.zohoapis.in',organizationId:'123'},async()=>Response.json({code:0}));await assert.rejects(client.get('/books/v3/purchaseorders?vendor_id=88'),/QUERY_NOT_ALLOWED/);await assert.rejects(client.get('/books/v3/bills?vendor_id=foreign'),/QUERY_NOT_ALLOWED/);await client.get('/books/v3/bills?vendor_id=88&page=1&per_page=200');assert.equal(client.requestCount(),1);});
