import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openPilotStore} from '../pilot/store.ts';import {readPilotView} from '../pilot/view-model.ts';
import {discoverLinkedDocuments} from '../pilot/linked-discovery.ts';import {handleLinkedDiscovery} from '../pilot/linked-discovery-http.ts';
const line={line_item_id:'l',quantity:1};
const so={salesorder_id:'1',salesorder_number:'SO-2627009',date:'2026-04-30',customer_id:'900',reference_number:'EXACT-REF',line_items:[line]};
const po=(id='2',owner='SO-2627009',bill='3')=>({purchaseorder_id:id,purchaseorder_number:'PO-'+id,date:'2026-05-01',custom_fields:[{label:'Sales Order No',value:owner}],bills:[{bill_id:bill}],line_items:[line]});
const inv=(id:string,customer='900',ref='EXACT-REF')=>({invoice_id:id,invoice_number:'INV-'+id,date:'2026-05-01',customer_id:customer,reference_number:ref,line_items:[line]});
const result=(body:object)=>({raw:JSON.stringify({code:0,...body})});
const list=(field:string,rows:object[],more=false)=>result({[field]:rows,page_context:{page:1,has_more_page:more}});
function fixture(){const root=mkdtempSync(join(tmpdir(),'v2-discovery-'));const s=openPilotStore(root),run=s.start('123');s.capture(run,'/books/v3/salesorders/1',result({salesorder:so}).raw);s.publishCapturedDetails();s.close();return root;}
const input=(root:string)=>({soId:'1',snapshot:readPilotView(root).snapshotId});
function transport(paths:string[]){return async(org:string,path:string)=>{assert.equal(org,'123');paths.push(path);
 if(path==='/books/v3/salesorders/1')return result({salesorder:so});
 if(path.includes('/purchaseorders?'))return list('purchaseorders',[{purchaseorder_id:'2',cf_sales_order_no:'SO-2627009'},{purchaseorder_id:'4',cf_sales_order_no:'SO-2627009'}]);
 if(path==='/books/v3/purchaseorders/2')return result({purchaseorder:po()});
 if(path==='/books/v3/purchaseorders/4')return result({purchaseorder:po('4','SO-9999999')});
 if(path==='/books/v3/bills/3')return result({bill:{bill_id:'3',bill_number:'B-3',date:'2026-05-01',line_items:[line]}});
 if(path.includes('/invoices?'))return list('invoices',[{invoice_id:'6'},{invoice_id:'7'},{invoice_id:'8'}]);
 if(path==='/books/v3/invoices/6')return result({invoice:inv('6')});
 if(path==='/books/v3/invoices/7')return result({invoice:inv('7','999')});
 if(path==='/books/v3/invoices/8')return result({invoice:inv('8','900','OTHER')});
 throw Error('Unexpected endpoint '+path);
};}
test('web discovery saves only related PO, explicit missing Bill and exact-customer/reference invoice, with no duplicate version on rerun',async()=>{
 const root=fixture();try{const paths:string[]=[];const r=await discoverLinkedDocuments(root,input(root),transport(paths));assert.equal(r.summary.added,3);assert.equal(r.summary.rejected,3);assert.equal(r.summary.status,'SEARCH_FINISHED');assert.equal(r.summary.coverage,'INCOMPLETE');assert.deepEqual(r.data.documents.map(d=>d.key).sort(),['BILL:3','INVOICE:6','PO:2','SO:1']);assert.equal(paths.filter(p=>p==='/books/v3/bills/3').length,1);assert.deepEqual(r.states,{});
 const before=r.data.snapshotId;const again=await discoverLinkedDocuments(root,input(root),transport([]));assert.equal(again.summary.added,0);assert.equal(again.summary.updated,0);assert.equal(again.data.snapshotId,before);
 const s=openPilotStore(root);assert.equal(s.publishCapturedDetails().published,0);s.close();
 }finally{rmSync(root,{recursive:true});}
});
test('truncated searches remain partial and do not acquire their rows',async()=>{const root=fixture();try{const paths:string[]=[];const r=await discoverLinkedDocuments(root,input(root),async(_org,p)=>{paths.push(p);return p.endsWith('/salesorders/1')?result({salesorder:so}):list(p.includes('purchaseorders')?'purchaseorders':'invoices',[],true);});assert.equal(r.summary.status,'PARTIAL');assert.equal(r.summary.added,0);assert.equal(paths.length,2);assert.equal(r.data.documents.length,1);}finally{rmSync(root,{recursive:true});}});
test('unknown or stale SO has no network requests; concurrent discovery is rejected',async()=>{const root=fixture();try{let calls=0;await assert.rejects(discoverLinkedDocuments(root,{...input(root),soId:'9'},async()=>{calls++;return result({});}),/NOT_ALLOWED/);await assert.rejects(discoverLinkedDocuments(root,{...input(root),snapshot:'0'.repeat(20)},async()=>{calls++;return result({});}),/SOURCE_CHANGED/);assert.equal(calls,0);
 let release!:(v:{raw:string})=>void;const pending=discoverLinkedDocuments(root,input(root),()=>new Promise(resolve=>{release=resolve;}));await assert.rejects(discoverLinkedDocuments(root,input(root),transport([])),/ALREADY_RUNNING/);release(result({salesorder:{...so,purchaseorders:'invalid'}}));const r=await pending;assert.equal(r.summary.status,'PARTIAL');
 }finally{rmSync(root,{recursive:true});}});
test('time limit exits safely before any source request; malformed detail is never later published',async()=>{const root=fixture();try{let ticks=0;const r=await discoverLinkedDocuments(root,input(root),()=>{throw Error('must not call');},()=>ticks++?60001:0);assert.equal(r.summary.requests,0);assert.equal(r.summary.status,'PARTIAL');
 const bad=await discoverLinkedDocuments(root,input(root),async()=>result({salesorder:{...so,salesorder_id:'999'}}));assert.equal(bad.summary.status,'PARTIAL');assert.equal(readPilotView(root).documents[0].version,'v1');const s=openPilotStore(root);assert.equal(s.publishCapturedDetails().published,0);s.close();
 }finally{rmSync(root,{recursive:true});}});
test('source changes in flight stop before publishing stale responses',async()=>{const root=fixture();try{const r=await discoverLinkedDocuments(root,input(root),async()=>{const s=openPilotStore(root),run=s.start('123');s.capture(run,'/books/v3/salesorders/1',result({salesorder:{...so,reference_number:'NEW'}}).raw);s.publishCapturedDetails();s.close();return result({salesorder:so});});assert.equal(r.summary.status,'PARTIAL');assert.equal(r.data.documents[0].referenceNumber,'NEW');}finally{rmSync(root,{recursive:true});}});
test('HTTP blocks production, foreign origin, no owner and injected targets',async()=>{let calls=0;const deps={environment:'development',owner:async()=>true,discover:async()=>{calls++;return {};}};const body={soId:'1',snapshot:'a'.repeat(20)};const request=(value:unknown=body,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/master-audit-v2/discovery',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(value)});
 assert.equal((await handleLinkedDiscovery(request(),{...deps,environment:'production'})).status,403);assert.equal((await handleLinkedDiscovery(request(body,'https://evil.test'),deps)).status,403);assert.equal((await handleLinkedDiscovery(request(),{...deps,owner:async()=>false})).status,401);assert.equal((await handleLinkedDiscovery(request({...body,endpoint:'/bills'}),deps)).status,400);assert.equal(calls,0);assert.equal((await handleLinkedDiscovery(request(),deps)).status,200);assert.equal(calls,1);
});
test('new-document compare-and-swap rejects an ID concurrently created elsewhere',()=>{const root=fixture();try{const s=openPilotStore(root),run=s.start('123');const old=s.capture(run,'/books/v3/purchaseorders/2',result({purchaseorder:po()}).raw);const other=s.capture(run,'/books/v3/purchaseorders/2',result({purchaseorder:{...po(),reference_number:'new'}}).raw);assert.equal(s.publishCapturedDetails(new Set([other.responseId])).published,1);assert.equal(s.publishCapturedDetails(new Set([old.responseId]),new Map([[old.responseId,null]])).failures.length,1);s.markRejectedResponse('123',old.responseId);s.close();assert.equal(readPilotView(root).documents.find(d=>d.type==='PO')?.referenceNumber,'new');}finally{rmSync(root,{recursive:true});}});
test('index pagination finds exact SO tokens on later pages and ignores similar numbers',async()=>{const root=fixture();try{const paths:string[]=[];const base=transport(paths);const r=await discoverLinkedDocuments(root,input(root),async(org,p)=>{if(p.includes('/purchaseorders?')){if(p.includes('page=1&'))return list('purchaseorders',[{purchaseorder_id:'99',cf_sales_order_no:'SO-26270090'}],true);return result({purchaseorders:[{purchaseorder_id:'2',cf_sales_order_no:'SO-2627009'}],page_context:{page:2,has_more_page:false}});}return base(org,p);});assert.equal(r.summary.poPages,2);assert.equal(r.summary.poIndexComplete,true);assert.equal(r.summary.added,3);assert.equal(paths.some(p=>p.endsWith('/99')),false);}finally{rmSync(root,{recursive:true});}});
test('hard request budget retains completed documents and leaves coverage partial',async()=>{const root=fixture();try{let calls=0;const r=await discoverLinkedDocuments(root,input(root),async(_org,p)=>{calls++;if(p.endsWith('/salesorders/1'))return result({salesorder:so});if(p.includes('/purchaseorders?'))return list('purchaseorders',Array.from({length:40},(_,i)=>({purchaseorder_id:String(i+100),cf_sales_order_no:'SO-2627009'})));if(p.includes('/purchaseorders/')){const id=p.split('/').at(-1)!;return result({purchaseorder:po(id,'SO-2627009',String(Number(id)+1000))});}if(p.includes('/bills/'))return result({bill:{bill_id:p.split('/').at(-1),bill_number:'Bill',date:'2026-05-01',line_items:[line]}});throw Error('unexpected');});assert.equal(calls,55);assert.equal(r.summary.requests,55);assert.equal(r.summary.status,'PARTIAL');assert.equal(r.data.documents.filter(d=>d.type==='PO').length,40);assert.ok(r.summary.issues.some(x=>x.includes('limit')));}finally{rmSync(root,{recursive:true});}});
