import test from 'node:test';import assert from 'node:assert/strict';
import {purchaseCoverage,coverageRefreshDocuments} from '../pilot/purchase-coverage.ts';
import {refreshSavedDocuments} from '../pilot/coverage-refresh.ts';
import type {PilotDocument,PilotView,PilotLine} from '../pilot/view-model.ts';
const line=(id:string,rate:string,extra:Partial<PilotLine>={})=>({id,name:'Installation',quantity:'1',unit:'job',purchaseRate:rate,parentLineId:null,parentDocumentId:null,...extra} as PilotLine);
const doc=(type:string,id:string,extra:Partial<PilotDocument>={})=>({key:type+':'+id,type,id,number:type+'-'+id,currency:'INR',priceTaxBasis:'EXCLUSIVE',billIds:[],invoiceIds:[],salesOrderIds:[],customerId:null,referenceNumber:null,owners:[],lines:[],...extra} as PilotDocument);
function fixture(){return {snapshotId:'a'.repeat(20),documents:[doc('SO','1'),doc('PO','2',{owners:['SO-1'],billIds:['3','3'],lines:[line('21','100.10')]}),doc('BILL','3',{lines:[line('31','10.10',{parentLineId:'21',parentDocumentId:'2'})]})],coverage:'INCOMPLETE',responseCount:0} as PilotView;}
test('deduplicates references, compares exact linked rates and never certifies final cost',()=>{const data=fixture(),r=purchaseCoverage(data,'1');assert.equal(r.bills.length,1);assert.equal(r.rateDifferences.length,1);assert.equal(r.rateDifferences[0].poRate,'100.10');assert.equal(r.complete,false);data.documents[2].lines[0].purchaseRate='100.100';assert.equal(purchaseCoverage(data,'1').rateDifferences.length,0);});
test('missing Bill evidence, no references and shared ownership remain explicit',()=>{const data=fixture();data.documents.push(doc('PO','4',{owners:['SO-1']}),doc('PO','5',{owners:['SO-1 & SO-2'],billIds:['99']}));const r=purchaseCoverage(data,'1');assert.deepEqual(r.missingBillIds,['99']);assert.equal(r.withoutBills[0].id,'4');assert.equal(r.shared[0].id,'5');assert.equal(coverageRefreshDocuments(data,'1').length,5);});
test('does not compare uncertain links, currencies, units, tax basis or shared allocation',()=>{
 for(const mutate of [(d:PilotView)=>{d.documents[2].lines[0].parentLineId=null;},(d:PilotView)=>{d.documents[2].currency='USD';},(d:PilotView)=>{d.documents[2].priceTaxBasis='INCLUSIVE';},(d:PilotView)=>{d.documents[2].lines[0].unit='hour';},(d:PilotView)=>{d.documents[1].owners=['SO-1 & SO-2'];},(d:PilotView)=>{d.documents[2].lines[0].purchaseRate=null;}]){const d=fixture();mutate(d);const r=purchaseCoverage(d,'1');assert.equal(r.rateDifferences.length,0);assert.equal(r.uncheckedLines,1);}
});
test('refresh chains new snapshots, publishes each success and stops on first failure without retry',async()=>{const data=fixture(),seen:string[]=[],published:string[]=[];await assert.rejects(refreshSavedDocuments(data,data.documents,{request:async input=>{seen.push(input.snapshot);if(seen.length===2)throw Error('timeout');return {data:{...data,snapshotId:'b'.repeat(20)},states:{},status:'CHANGED'};},progress:()=>{},published:r=>published.push(r.data.snapshotId),stopped:()=>false}),/timeout/);assert.deepEqual(seen,['a'.repeat(20),'b'.repeat(20)]);assert.deepEqual(published,['b'.repeat(20)]);});
test('stop after current document preserves progress and sends no later request',async()=>{const data=fixture();let stop=false,calls=0;const r=await refreshSavedDocuments(data,[...data.documents,data.documents[0]],{request:async()=>{calls++;return {data,states:{},status:'UNCHANGED'};},progress:()=>{},published:()=>{stop=true;},stopped:()=>stop});assert.equal(calls,1);assert.deepEqual(r,{completed:1,total:3,stopped:true});});
