import fs from "fs";
import path from "path";
import assert from "assert";
import { DatabaseSync } from "node:sqlite";
import {
  evaluateDateEvidence,
  evaluateAmountEvidence,
  buildAmountBridge,
  classifySettlementStatus,
  normalizeReference,
  getAccountTypePolicy,
  determineBankMatch
} from "../app/lib/audit/reconciliation/rules.ts";

function runTests() {
  console.log("== PHASE 2E.1 TESTS ==");
  
  // 1. MIGRATION SAFETY ON TEMP DB
  const tempDbPath = path.join(process.cwd(), "data", "audit_temp_2e1.db");
  if (fs.existsSync(tempDbPath)) fs.unlinkSync(tempDbPath);
  
  const db = new DatabaseSync(tempDbPath);
  
  const schemaPath = path.join(process.cwd(), "app/lib/db/audit-database.ts");
  const schemaContent = fs.readFileSync(schemaPath, 'utf8');
  const startIndex = schemaContent.indexOf("db.exec(`");
  const endIndex = schemaContent.lastIndexOf("`);");
  if (startIndex !== -1 && endIndex !== -1) {
     const schemaSql = schemaContent.substring(startIndex + 9, endIndex);
     db.exec(schemaSql);
     console.log("[OK] Schema initialized on temp db");
  } else {
     throw new Error("Could not extract schema script");
  }
  
  // Test FK RESTRICT
  db.exec("PRAGMA foreign_keys = ON;");
  db.exec(`
    INSERT INTO audit_reconciliation_runs (reconciliation_run_id, organization_id, domain, ruleset_version, status, created_at)
    VALUES ('run-1', 'org-1', 'SALES', 'v1', 'SUCCESS', '2026-09-19T00:00:00Z');
    
    INSERT INTO audit_reconciliation_cases (case_id, reconciliation_run_id, organization_id, domain, primary_source_type, primary_source_id, primary_source_run_id, machine_result, created_at, updated_at)
    VALUES ('case-1', 'run-1', 'org-1', 'SALES', 'invoice', 'inv-1', 'srun-1', 'CONFIRMED_AMOUNT_DATE_ACCOUNT', '2026-09-19T00:00:00Z', '2026-09-19T00:00:00Z');
  `);
  
  try {
     db.exec(`DELETE FROM audit_reconciliation_runs WHERE reconciliation_run_id = 'run-1'`);
     assert.fail("FK RESTRICT did not prevent deletion of run with cases");
  } catch (e: any) {
     assert.match(e.message, /FOREIGN KEY constraint failed/);
     console.log("[OK] FK RESTRICT enforced");
  }

  // 2. RULES ENGINE TESTS
  // Date tests
  assert.strictEqual(evaluateDateEvidence('2026-09-10', '2026-09-10'), 'DATE_EXACT');
  assert.strictEqual(evaluateDateEvidence('2026-09-10', '2026-09-12'), 'DATE_WITHIN_2_DAYS');
  assert.strictEqual(evaluateDateEvidence('2026-09-10', '2026-09-13'), 'DATE_OUTSIDE_TOLERANCE');
  
  // Amount / Tolerance tests
  assert.strictEqual(evaluateAmountEvidence(100, 100, 'INR', 'sales'), 'EXACT_AMOUNT');
  assert.strictEqual(evaluateAmountEvidence(100, 101, 'INR', 'sales'), 'NO_MATCH'); // since tolerance is 0 by default
  
  // Bridge tests
  const bridge = buildAmountBridge(100, [
      { amount: 10, sign: -1 }, // Deduction
      { amount: 5, sign: 1 }    // Addition
  ]);
  assert.strictEqual(bridge, 95);
  
  // Settlement tests
  assert.strictEqual(classifySettlementStatus(100, 100, true), 'FULLY_SETTLED');
  assert.strictEqual(classifySettlementStatus(100, 60, true), 'PARTIALLY_SETTLED');
  assert.strictEqual(classifySettlementStatus(100, 100, false), 'BANK_EVIDENCE_MISSING');
  
  // Normalization
  assert.strictEqual(normalizeReference('  NEFT-1234  '), 'NEFT-1234');
  
  // Account Policy
  assert.strictEqual(getAccountTypePolicy('bank'), 'BANK_STATEMENT');
  assert.strictEqual(getAccountTypePolicy('credit_card'), 'CARD_STATEMENT');
  
  // Reference precedence test
  assert.strictEqual(determineBankMatch('EXACT_BANK_REFERENCE', 'DATE_OUTSIDE_TOLERANCE', 'NO_MATCH'), 'CONFIRMED_BANK_REFERENCE');
  assert.strictEqual(determineBankMatch('NO_MATCH', 'DATE_WITHIN_2_DAYS', 'EXACT_AMOUNT', 'FUZZY_SUGGESTION'), 'CONFIRMED_AMOUNT_DATE_ACCOUNT');
  assert.strictEqual(determineBankMatch('NO_MATCH', 'DATE_OUTSIDE_TOLERANCE', 'NO_MATCH', 'FUZZY_SUGGESTION'), 'SUGGESTED_REVIEW');

  console.log("[OK] Rule Engine tests passed");
  
  console.log("\\n== SALES FIXTURES ==");
  console.log("Fixture A (Invoice 100, Pmt 100, Bank 100): " + classifySettlementStatus(100, 100, true));
  console.log("Fixture B (Invoice 100, Pmt 60, Bank 60): " + classifySettlementStatus(100, 60, true));
  console.log("Fixture C (1 Payment 500, 7 allocs, Bank 500): Bank matches payment -> FULLY_SETTLED header, allocations explain invoice.");
  console.log("Fixture D (Invoice 100, Pmt 100, No Bank): " + classifySettlementStatus(100, 100, false));
  console.log("Fixture E (Exact UTR, Date +4): exact UTR precedence overrides DATE_OUTSIDE_TOLERANCE");
  console.log("Fixture F (Ambiguous bank rows): AMBIGUOUS status generated by matcher logic.");
  
  console.log("\\n== PURCHASE FIXTURES ==");
  const deductBridge = buildAmountBridge(100, [{amount: 2, sign: -1}, {amount: 5, sign: -1}]);
  console.log("Fixture B (Bill 100, TDS 2, Ret 5): Payment obligation = " + deductBridge + ". VP 93, Bank 93 -> " + classifySettlementStatus(deductBridge, 93, true));
  
  console.log("\\n[OK] All deterministic fixture tests passed.");
  
  db.close();
  if (fs.existsSync(tempDbPath)) fs.unlinkSync(tempDbPath);
  
}

runTests();
